### ISSUE TITLE
BusinessPool#initPool(ServerTransportConfig transportConfig) 方法的线程池配置

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-rpc#104]
您好！

BusinessPool#initPool(ServerTransportConfig transportConfig) 方法的 TODO 是否可以使用 `rpc-config-default.json` 文件中配置？

但目前 ServerTransportConfig 配置类中没有 server.pool.core 常量和 server.pool.aliveTime 常量。目前代码中的 fixed 类型线程池的 core 线程数默认是 200，aliveTime 是 0，如果错误使用了，是否有问题呢？

如果可以使用 `rpc-config-default.json` 的话，是否有必要加入这两个常量供这个方法使用？还是说这里可能另有考量？

**Comment by leizhiyuan** [comment]
目前使用的是com.alipay.sofa.rpc.server.BusinessPool#initPool(com.alipay.sofa.rpc.config.ServerConfig)

rpc 不在 sofaboot 中,而是单独使用的时候,这个值根据不同的协议,需要用户自己设置ServerConfig的值.


而在starter 中会从 application 中读取.每个协议有不同的 key.

**Comment by stateIs0** [comment]
好的，谢谢解答。
