### ISSUE TITLE
服务消费方调用之后想断开连接，请问该如何配置？

### ISSUE THREAD

**Issue by mingxing47** [alipay/sofa-rpc#108]
最近准备把sofa-rpc引入公司内部产品中。现在有个场景是需要在服务消费方单次调用之后断开连接。
今天实验的结果是，消费方单次调用之后客户端没有断开连接，还一直在连接。
查了文档之后没有找到这方面的配置，请问该如何配置实现这一功能？谢谢~

或者是否是我理解有错误

**Comment by mingxing47** [comment]
hi，因为我们这个rpc调用的频率不高，因此调用后想断开连接，避免占用资源。需要时再做重连。

**Comment by leizhiyuan** [comment]
@mingxing47 socket连接本身占用的资源? 这种占用资源基本可以忽略的吧.

**Comment by mingxing47** [comment]
@leizhiyuan 好的，那我就先这样使用，谢谢~

**Comment by leizhiyuan** [comment]
@mingxing47 恩,好的,长连接有个好处是你下次新调用的时候,由于连接已经建立好了.所以调用会很快,没有重新建立连接的过程,不阻塞你的业务调用. 

如果再有问题,再沟通.感谢
