### ISSUE TITLE
请问是否有支持Protocol Buffer的计划呢？

### ISSUE THREAD

**Issue by jewin** [alipay/sofa-rpc#111]

**Comment by ujjboy** [comment]
`bolt` 协议目前就支持 `protobuf`.  需要请求参数和返回值都是 `protobuf` 对象。

**Comment by khotyn** [comment]
@ujjboy 可以搞一个 Sample 或者文章出来，😆

**Comment by leizhiyuan** [comment]
恩,这两天我在 starter 里写一个 pb+bolt 的场景demo.顺便完善一下 wiki.

**Comment by jewin** [comment]
看了源码，把请求参数的serializeType设置为11就可以支持pb的编解码了， 有没有什么优雅的方式来动态的调整这个序列化类型呢？

**Comment by jewin** [comment]
在目前的5.4.0版本下，如果存在服务提供方存在多种序列化协议，那么该如何切换呢？
我想的是在过滤器里去判断SofaRequest的类型来确定序列化协议，不知道这个思路对不对

**Comment by ujjboy** [comment]
@jewin 看了这里的例子 https://github.com/alipay/sofa-rpc/tree/master/example/src/test/java/com/alipay/sofa/rpc/protobuf   

使用protobuf有几个注意点：
- 接口的定义里，请求和参数得是protobuf对象
- 客户端在发起请求的时候可以设置序列化类型

**Comment by ujjboy** [comment]
文档还需要完善。
