### ISSUE TITLE
服务器存在多个IP的情况下，可以指定IP向注册中心注册码？

### ISSUE THREAD

**Issue by jewin** [alipay/sofa-rpc#114]

**Comment by ujjboy** [comment]
@jewin  
除了上面指定地址的普通场景下，如果还有如下需求：
- 如果要特别指定绑定服务的主机，使用`ServerConfig#setBoundHost` 默认 `serverConfig.getHost()`
- 如果要特别指定注册到注册中心的地址（和发布服务的地址不一致），可以使用`ServerConfig#setVirtualHost` 默认 `serverConfig.getHost()`

**Comment by jewin** [comment]
不能在xml里指定吗

**Comment by leizhiyuan** [comment]
starter 场景下的使用,暂时没有做转换.

https://github.com/alipay/sofa-rpc-boot-projects/issues/42

issue 见这里.下周会支持.

**Comment by jewin** [comment]
期待新版本。
目前在启动参数中手工设置SystemInfo.setLocalHost("127.0.0.1"); 强制指定ip。
