### ISSUE TITLE
ConfigListener add a method or parameter to distinguish config and overrides

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-rpc#117]
### Your question

ConfigListener add a method or parameter to distinguish config and overrides

### Your scenes

1.add a paramter
2.add a new Listener, maybe overideListener

### Your advice

I prefer to 1.
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
Now:
- `com.alipay.sofa.rpc.listener.ConfigListener#configChanged`  is for change config of interface.
- `com.alipay.sofa.rpc.listener.ConfigListener#attrUpdated` is for change field value of provider&consumer.

Do you mean config of provider&consumer?  Can you give any examples?

**Comment by leizhiyuan** [comment]
ok. This means configChanged is not used now.
