### ISSUE TITLE
通过zookeeper连接时本地服务、消费列表维护，以及网络断开后的服务发现问题

### ISSUE THREAD

**Issue by guzhangyu** [alipay/sofa-rpc#118]
### 后来网络连上了，zookeeper的连接不报错了，服务方的状态也显示为RECONNECTED了，但是消费方调用服务方的方法仍然会报服务找不到的错误。

SofaRouteException: RPC-02306: 没有获得服务[com.unitymob.auth.api.AuthService:1.0]的调用地址，请检查服务是否已经推送 
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
### Environment

- SOFARPC version:2.3.2
- JVM version (e.g. `java -version`):1.8.0
- OS version (e.g. `uname -a`): win10
- Maven version:
- IDE version:

**Comment by guzhangyu** [comment]
服务端客户端同时和注册中心断开

**Comment by davis1214** [comment]
客户端有zookeeper path的监听事件。当服务端非优雅方式关闭，客户端会收到remove provider的事件。用于清除客户端服务调用列表。

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/pull/337
