### ISSUE TITLE
发展路线 & 任务认领  文档翻译

### ISSUE THREAD

**Issue by liangyuanpeng** [alipay/sofa-rpc#119]
### Your question

在  发展路线 & 任务认领  中 文档翻译 这个任务主要是针对哪方面的一个文档翻译呢？
举个例子来说的话,目前有吗

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
文档目前我们一般考虑到对内用户的友好,目前只是提供了中文版的文档,如果有兴趣,可以将一些 quickstart 相关的翻译为英文.

**Comment by liangyuanpeng** [comment]
明白了
