### ISSUE TITLE
配置zookeeper的注册发现服务的方式的时候，本地的注册目录不会生成

### ISSUE THREAD

**Issue by guzhangyu** [alipay/sofa-rpc#120]
###  配置方式 com.alipay.sofa.rpc.registry.address=zookeeper://xxx:2181?file=D:/registry
ps: 本地的默认路径下System.getProperty("user.home") + "/localFileRegistry/localRegistry.reg" 该文件时存在的，但是里面的内容没有包含当前的服务。

### Environment

- SOFARPC version:2.3.2
- JVM version (e.g. `java -version`):1.8.0
- OS version (e.g. `uname -a`):win10
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
localRegistry.reg 只有在 使用本地注册中心的才会生成, zk 不会生成,地址保存在 zk 里面

**Comment by leizhiyuan** [comment]
对 zk 的配置
```
com.alipay.sofa.rpc.registry.address=zookeeper://xxx:2181
```

这样就行了.没有后面的.

**Comment by guzhangyu** [comment]
哦，我是看了 https://github.com/alipay/sofa-rpc-boot-projects/wiki/Registry的说法，说到会生成本地注册文件。
![default](https://user-images.githubusercontent.com/5295320/40093201-a70fde02-58f3-11e8-8917-ad1a8538013d.png)

**Comment by leizhiyuan** [comment]
@guanchao-yang  之后的版本会考虑支持,有兴趣也可以直接提 pr.
