### ISSUE TITLE
关于停止客户端线程

### ISSUE THREAD

**Issue by ddrw** [alipay/sofa-rpc#132]
请问，当客户端发送完请求，得到服务端返回的结果后，如何把客户端发请求时的线程停止掉

**Comment by JervyShi** [comment]
客户端请求发起的线程生命周期都在应用处管理的，如 HTTP 请求触发的线程生命周期随一次 HTTP 请求结束就结束掉了，如果是定时任务类的，看任务的执行生命周期，这部分生命周期不在 RPC 内管理。

**Comment by khotyn** [comment]
@ddrw 如果有问题，请再打开 ISSUE，客户端发送请求是直接在业务线程中完成的。
