### ISSUE TITLE
Use embedded zookeeper for integration test.

### ISSUE THREAD

**Issue by ujjboy** [alipay/sofa-rpc#135]
### Your question

In `travis-ci`, we install zookeeper before run integration test. And in dev mode, we must run local zookeeper server before run `mvn test -Pit-test`.

### Your advice

Use embedded zookeeper instead of it.

for example:

```
<dependency>
  <groupId>org.apache.curator</groupId>
  <artifactId>curator-test</artifactId>
</dependency>
```

**Comment by leizhiyuan** [comment]
这个我来改吧
