### ISSUE TITLE
Support kyro serialization

### ISSUE THREAD

**Issue by ujjboy** [alipay/sofa-rpc#139]
### Your question

[Kryo](https://github.com/EsotericSoftware/kryo) is a fast and efficient object graph serialization framework for Java. The goals of the project are speed, efficiency, and an easy to use API. The project is useful any time objects need to be persisted, whether to a file, database, or over the network.

### Your advice

Add `Serializer` extension of [Kryo](https://github.com/EsotericSoftware/kryo).

The example is https://github.com/alipay/sofa-rpc/tree/master/extension-impl/codec-protobuf

**Comment by leizhiyuan** [comment]
kryo 对字段新增不友好,在rpc 场景下不太适合,待定.
