### ISSUE TITLE
Support jackson serialization

### ISSUE THREAD

**Issue by ujjboy** [alipay/sofa-rpc#140]
### Your question

Jackson is a suite of data-processing tools for Java (and the JVM platform), including the flagship streaming JSON parser / generator library, and so on.

- https://github.com/FasterXML/jackson
- https://github.com/FasterXML/jackson-databind

### Your advice

Add `Serializer` extension of Jackson

The example is https://github.com/alipay/sofa-rpc/tree/master/extension-impl/codec-protobuf

**Comment by xt8469** [comment]
这个Help Wanted完成了么

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/pull/239 是的。待合并。
