### ISSUE TITLE
有关参数兼容性问题

### ISSUE THREAD

**Issue by AJ-Liang** [alipay/sofa-rpc#157]
sofa是否支持方法增删入参？
如：sayHello(String name, int age) 改为 sayHello(String name)
那在老的客户端调用新服务是否有兼容性问题呢？

**Comment by ujjboy** [comment]
不能兼容参数列表发生变化，这种情况建议用新方法代替。

但如果你的参数是个自定义对象，hessian是支持增减字段的。

**Comment by AJ-Liang** [comment]
了解，谢谢。
看到方法入参的序列化是顺序的，所以产生这样的疑问。
