### ISSUE TITLE
怎么做灰度发布

### ISSUE THREAD

**Issue by icc99** [alipay/sofa-rpc#160]
### Your question

怎么做灰度发布？

### Your scenes

上线了一个新的服务，但不希望上线之后就能被所有的客户端调用

### Your advice

能不能类似于dubbo， 服务可以加版本号？
### Environment

- SOFARPC version:

**Comment by khotyn** [comment]
@icc99 用 uniqueId 即可，和 Dubbo 的 version 一样的作用。

**Comment by jjtyro** [comment]
@khotyn 如何利用uniqueId做灰度呢？ 有无示例提供？ 我是想利用Sofa-Rpc平身的权重负载均衡来在不同版本服务提供者间的分流。

**Comment by jjtyro** [comment]
@khotyn Sofa-Rpc服务端是要根据interfaceId与uniqueId查找服务对象的，如果uniqueId不一致，就是客户端服务发现能路由请求到新版本服务提供端，也会报错的。

**Comment by JervyShi** [comment]
interfaceId 和 uniqueId 确定唯一一个服务，服务消费者指定 uniqueId A 之后，不会调用掉 uniqueId B 的服务，A 和 B 之间不会互相发现。

**Comment by jjtyro** [comment]
@JervyShi 可以调用到的， 因为虽然客户端初始起动，订单zookeeper上服务提供者时，返回的服务端列表是通过protocal、interfaceID与uniqueId过滤的， 但， 当zookeeper有新的服务提供者注册时，客户端服务订阅listener又采取了不理会uniqueId的过滤方式。 这时，客户端  的 请求是会路由到新的服务端的，虽然这个服务端不提供uniqueId A的服务

**Comment by jjtyro** [comment]
@JervyShi 测试过程：
起动uniqueId A服务；
客户端setUniqueid = A， 启动，不停发请求；
起动uniqueId B服务；

uniqueId B收到请求，报错： 未找到业务服务，服务名称：[com.alipay.sofa.rpc.protobuf.ProtoService:A]

**Comment by JervyShi** [comment]
@jjtyro 排查了一下，这里实现上不符合预期，我们修复下。

**Comment by jjtyro** [comment]
@JervyShi 嗯，修复成不可见方式？

**Comment by khotyn** [comment]
@jjtyro 应该就是不可见的方式，同样的接口，不用的 UniqueId，对于 SOFARPC 来说就应该是不同的服务。

**Comment by JervyShi** [comment]
@jjtyro 这个问题将会在 https://github.com/alipay/sofa-rpc/issues/166 中跟踪修复。

**Comment by jjtyro** [comment]
@khotyn 那问题回来了，只基于sofa-rpc现有的框架，不借用其他工具或应用编码，能否实现A/B及蓝绿灰度发布？

**Comment by khotyn** [comment]
A/B 和蓝绿还是需要配合外围的平台一起来配合实现的。

**Comment by jjtyro** [comment]
@khotyn 明白了，谢谢！
