### ISSUE TITLE
客户端Http2协议将来会不会支持Prior-Knowledge方式

### ISSUE THREAD

**Issue by jjtyro** [alipay/sofa-rpc#164]
原是想试验在Sofa-Rpc客户端与服务端之间使用envoy或linkerd，没能通过，报错。
使用wireshark捕获了下往来数据包，发现sofa-rpc是通过http upgrade h2c与服务端协商是否可进入Http2，可不管是envoy还是linkerd，都不支持这种方式，只支持preface方式。

粗略看了下sofa代码，好象是没有在upgrade h2c与preface方式间切换的配置。

以后会支持吗？

**Comment by JervyShi** [comment]
@jjtyro 有兴趣提 PR 共建么？

**Comment by jjtyro** [comment]
@JervyShi 提了个PR，检查没通过，日志里提示：
"[0K$ sh ./tools/check_format.sh
Please commit your change before run this shell, un commit files:
M extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientInitializer.java"
但我这边这个代码文件是提交了的

**Comment by JervyShi** [comment]
CI 执行时，会 run 

```
  - mvn clean install -Pci-install -B -U -e
  - sh ./tools/check_format.sh
```
`mvn clean install` 时会触发格式化插件格式化代码，你可以在本地执行下 `mvn clean install` 做下代码格式化，然后把格式化后的改动提交。
