### ISSUE TITLE
目前决定唯一服务的元素是有几个

### ISSUE THREAD

**Issue by liangyuanpeng** [alipay/sofa-rpc#182]
### Your question

在5.4的sofa-rpc版本中，InterfaceId相同，ServerConfig不同端口算是两个服务提供者

现在我发现在5.4.1-SNAPSHOT版本的sofa-rpc的版本中，InterfaceId相同，ServerConfig端口不同,算是同一个服务提供者，因为uniqueId相同

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.4.1-SNAPSHOT
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): mac
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
目前 `interfaceId` + `uniqueId` + `protocol` 确定唯一服务。

**Comment by liangyuanpeng** [comment]
有这个疑问是因为我希望通过zookeeper订阅InterfaceId相同的服务，但是如果服务提供者启动时指定了UniqueId，而消费者在启动时想通过zookeeper订阅服务是找不到这个服务的，除非指定UniqueId，这样的话又只能找到一个服务提供者

按照目前的思路，需要订阅InterfaceId相同的服务列表，需要如何做到？

**Comment by JervyShi** [comment]
@liangyuanpeng 

> 需要订阅InterfaceId相同的服务列表

这个和目前的设计逻辑是相悖的，`ZookeeperRegistry` 类的注释上有描述当前的服务提供方和订阅方在 Zookeeper 上的存储路径结构，uniqueId 是每个服务提供方的一个属性，在 `ZookeeperRegistry#subscribe` 中接收到的其实就是某个 InterfaceId 的所有服务提供方列表，只是实现上根据目前我们设计的隔离结构做了过滤，如果你期望直接订阅，可以继承 `ZookeeperRegistry` 做个性化的列表过滤实现。

**Comment by liangyuanpeng** [comment]
@JervyShi 
那按照目前的设计，服务方需要做集群处理，如何进行操作

**Comment by liangyuanpeng** [comment]
明白了，通过
``
ProviderConfig#setRepeatedExportLimit
``
设置为-1即可重复发布
