### ISSUE TITLE
消费者在配置注册中心后再设置了直连地址，订阅的服务直接使用的是直连地址的服务

### ISSUE THREAD

**Issue by liangyuanpeng** [alipay/sofa-rpc#183]
### Describe the bug

在 #178  中提到的一个问题，在这里发起一个新的issue

配置了注册中心后再设置直连地址，如果直连地址不存在，则抛出找不到服务的异常

看了一下源码，如果是有配置注册中心的情况下，并且消费者显示的配置了直连地址

在添加调用链的时候进入下面
``
RegistryRouter#needToLoad
``
的方法，也是判断消费者ConsumerConfig是否有设置直连地址DirectUrl，

在获取订阅的服务时
``
DefaultConsumerBootstrap#subscribe
``
也是直接判断是否有设置直连地址DirectUrl，即使配置了注册中心也是忽略

从效果上来看，这是否是设计本身就是这样设计的？

是否考虑过如果直连地址的服务有异常则从注册中心获取服务

### Environment

- SOFARPC version:5.4.1-SNAPSHOT
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by jinchaoxiang** [comment]
请问消费者如何关闭直连？

**Comment by liangyuanpeng** [comment]
@jinchaoxiang 

消费者配置ConsumerConfig没有设置directUrl值，则不会进行直连

**Comment by jinchaoxiang** [comment]
`com.alipay.remoting.exception.RemotingException: Create connection failed. The address is bolt://10.42.1.39:12200?uniqueId=&version=1`
请问我这个地址是否还是通过直连方式
```
 RegistryConfig registryConfig = this.registryConfig();
        ConsumerConfig<IIntegralService> consumer = new ConsumerConfig<IIntegralService>();
        consumer.setInterfaceId(IIntegralService.class.getName())
                .setRegistry(registryConfig)
                //.setCheck(true)
                .setRetries(2)
                .setTimeout(20000);
        IIntegralService iIntegralService = consumer.refer();
        return iIntegralService;
```
这是我的配置

**Comment by liangyuanpeng** [comment]
看日志确实是直连的




email：liangyuanpengem@163.com

在2018年06月19日 08:21，jinchaoxiang 写道：

com.alipay.remoting.exception.RemotingException: Create connection failed. The address is bolt://10.42.1.39:12200?uniqueId=&version=1
请问我这个地址是否还是通过直连方式

 RegistryConfig registryConfig = this.registryConfig();
        ConsumerConfig<IIntegralService> consumer = new ConsumerConfig<IIntegralService>();
        consumer.setInterfaceId(IIntegralService.class.getName())
                .setRegistry(registryConfig)
                //.setCheck(true)
                .setRetries(2)
                .setTimeout(20000);
        IIntegralService iIntegralService = consumer.refer();
        return iIntegralService;


这是我的配置

**Comment by leizhiyuan** [comment]
@jinchaoxiang 麻烦将你的工程方便的话, push 到你自己的公开仓库.我来看下.

**Comment by adleader** [comment]
我也遇到了类似的问题，我只是使用了sofa_rpc，采用直连的方式，目前的项目是传统的web project项目，A项目在应用服务器启动时候Listener中添加了ConsumerConfig作为客户端的配置，B项目在应用服务器启动时候Listener中添加了ServerConfig初始化了服务端。B项目做重启操作，不是关闭应用服务器再打开，而是Reload。这时候A项目作为客户端就连不上B项目了。只有关闭B项目的应用服务器再打开才可以连接，在这个过程A项目没有做任何重启关闭操作。

**Comment by JervyShi** [comment]
@liangyuanpeng @adleader 此问题已经在 https://github.com/alipay/sofa-rpc/pull/180 修复，随 release 版本 5.4.1 发布后可以再试下。

**Comment by ujjboy** [comment]
在 `settings.xml` 里增加 SNAPSHOT 仓库。

```xml
<settings>
    <profiles>
        <profile>
            <id>s-sonatype-snapshots</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>public-snapshots</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>public-snapshots</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
</settings>
```

就可以使用我们的 SNAPSHOT 版本。

```
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-rpc-all</artifactId>
            <version>5.4.1-SNAPSHOT</version>
        </dependency>
```

**Comment by adleader** [comment]
还是不太稳定，有一定概率出现com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-02306: 没有获得服务[com.xxx.rpcload.service.RpcService:1.0]的调用地址，请检查服务是否已经推送

**Comment by leizhiyuan** [comment]
@adleader 双检锁.防并发的.

**Comment by adleader** [comment]
直连配置，还是reload服务端的问题，服务端reload了，在客户端的“存活列表”，“亚健康列表”中找不到抽象的服务提供列表“ProviderInfo”，最终ClientTransport为null，导致throw noAvailableProviderException(message.getTargetServiceUniqueName());异常。

**Comment by liangyuanpeng** [comment]
最好可以提供对应的代码，能更好的排查问题

**Comment by adleader** [comment]
自己又调整了一下，之前客户端的ConsumerConfig在应用服务器启动时static了，是一个全局的，如果服务端重启了，之前初始化的static的ConsumerConfig应该被判定为无效。如果客户端每次调用都new ConsumerConfig就不存在这个问题。ConsumerConfig在refer()的时候应该有个机制检查一下。如果之前的refer()已失效，那么重新初始化一下。如果每次都new 还有一个setRepeatedReferLimit参数需要配置。
两个maven webapp的项目，打了个包传网盘上了。谁有时间帮忙看一下。
https://share.weiyun.com/53midJz
https://share.weiyun.com/5OppqUV
一个server一个client，部署在tomcat 下测试的，client中有个WebRpcClient作为Consumer调用服务。
