### ISSUE TITLE
日志输出问题

### ISSUE THREAD

**Issue by adleader** [alipay/sofa-rpc#185]
看了文档，没有日志输出相关的配置。继续看代码，发现com.alipay.sofa.rpc.log和com.alipay.remoting.log分别定义了log输出，集成到其他项目中如何修改此处的日志输出配置。不知如何解决，望解答。

**Comment by adleader** [comment]
自己又翻了翻代码，sofa-common-tools提供了日志输出的一些管理。com.alipay.sofa.common.log.Constants

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc-boot-projects/wiki/Settings#applicationproperties-%E9%85%8D%E7%BD%AE

@adleader 以 starter 进行集成,这两项做日志配置.

```

logging.level.com.alipay.sofa.rpc.boot | sofa-rpc-boot-start的日志级别(starter自身的日志) | info
-- | -- | --
logging.level.com.alipay.sofa.rpc | sofa-rpc的日志级别(sofa-rpc核心日志基本在这里) | info


```

**Comment by adleader** [comment]
@leizhiyuan 问题已解决，多谢解答。
