### ISSUE TITLE
Server端对http2 stream id的判断

### ISSUE THREAD

**Issue by jjtyro** [alipay/sofa-rpc#187]
在[Http2ServerChannelHandler](https://github.com/alipay/sofa-rpc/blob/e5fdd064eb1ec99c92387df7a09d842268e17cc8/extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ServerChannelHandler.java#L125)里，使用streamId>1来判断是否是setting包，这个在使用其他第三方网关中转sofa-client请求时，会遇到问题，如果网关连接sofa-rpc server，重新采取新的streamId编号，当数据包走到这个地方时，streamId可能是1。
有没有其他方式去代替这种通过stream id来判断的方法？

**Comment by leizhiyuan** [comment]
```
com.alipay.sofa.rpc.transport.http.Http2ServerChannelHandler#userEventTriggered
 @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
        /*
         * Handles the cleartext HTTP upgrade event. If an upgrade occurred, sends a simple response via HTTP/2
         * on stream 1 (the stream specifically reserved for cleartext HTTP upgrade).
         */
        if (evt instanceof HttpServerUpgradeHandler.UpgradeEvent) {
            HttpServerUpgradeHandler.UpgradeEvent upgradeEvent =
                    (HttpServerUpgradeHandler.UpgradeEvent) evt;
            onHeadersRead(ctx, 1, http1HeadersToHttp2Headers(upgradeEvent.upgradeRequest()), 0, true);
        }
        super.userEventTriggered(ctx, evt);
    }


```

这个 id =1 是我们代码自己生成的.所以理论上网关转发不会有问题.netty 的代码里也有类似的处理,可以看看.

**Comment by jjtyro** [comment]
噢，因为网关，比如：envoy，是以Priorknowledge连接的，不走upgrade，而且有可能不是1:1对等建立连接，所以出现了stream id＝1的data包。 
上面的代码逻辑，没太理解，既然onHeadersRead不理stream id＝1，那在这里call一下，是有什么后续处理？

**Comment by leizhiyuan** [comment]
目前没用到,之后可能会使用.

**Comment by jjtyro** [comment]
@leizhiyuan 了解啦！谢谢！

**Comment by leizhiyuan** [comment]
好的,使用有问题,欢迎再开 issue 或者提 pr. 这个我先关掉了.
