### ISSUE TITLE
com.alipay.sofa.rpc.client.AllConnectConnectionHolder.getAvailableClientTransport有没有陷入无限递归导致栈溢出的可能

### ISSUE THREAD

**Issue by ZZMarquis** [alipay/sofa-rpc#199]
### Your question

com.alipay.sofa.rpc.client.AllConnectConnectionHolder.getAvailableClientTransport有没有陷入无限递归导致栈溢出的可能

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
@ZZMarquis which line has the risk? please provide more info ?

**Comment by leizhiyuan** [comment]
那我先关闭了,如果有疑问,可以再打开.
