### ISSUE TITLE
怎样把第三方rest服务注册到注册中心

### ISSUE THREAD

**Issue by bulong0721** [alipay/sofa-rpc#203]
### Your question
怎样把第三方rest服务注册到注册中心
describe your question clearly

### Your scenes
其他小组或第三方已经存在的rest服务没有在注册中心，怎样将这些服务收集并注册到注册中心中（不想用directUrl，希望收集过一次可以供其他人复用所以考虑把providerConfig收集进注册中心）。
describe your use scenes (why need this feature)

### Your advice
1，可否扩展支持注册中心，添加新注册中心或组合注册中心？
2，建议directUrl能够从配置文件或配置中心读取，可以在多环境中使用不同地址。
describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@bulong0721  
1. 注册中心是可扩展的，扩展 `com.alipay.sofa.rpc.registry.Registry` 接口即可。
2. directUrl 配置值的读取外层代码可以自己做，例如通过 Spring的 profiler 等，根据自己的程序决定。如果是一个统一的配置中心管理多环境的直连地址配置的话，可以考虑将这个配置中心获取地址的地方包装成一个注册中心扩展实现。

**Comment by bulong0721** [comment]
非常感谢你的回复，补充一下，我是使用annotation方式，如果使用xml或编程式都没有问题。
