### ISSUE TITLE
rpc调用，提供者抛异常，调用方没有感知

### ISSUE THREAD

**Issue by guzhangyu** [alipay/sofa-rpc#204]
### Describe the bug

rpc调用，提供者抛异常，调用方没有感知

### Expected behavior
rpc 调用，提供者抛异常时，调用方需要感知

### Actual behavior
rpc调用，提供者抛异常，调用方没有感知

### Steps to reproduce
调用方远程调用服务方方法

### Minimal yet complete reproducer code (or GitHub URL to code)
服务方:
 public void testCustomException() {
        logger.info("调用到了aTest");
        throw new CustomException(AuthErrorMsg.LoginNameError);
    }
调用方：
   @GetMapping(value = "/testEx")
    public String testEx() {
        logger.info("调用远程接口");
        this.authService.testCustomException();
        return "yes";
    }
### Environment

- SOFARPC version: 5.4.1
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):mac 
- Maven version:3.3
- IDE version:

**Comment by JervyShi** [comment]
@guzhangyu SOFA RPC 是可以传递异常的，你可以在你的 github repo 中提供一个可复现工程么？我依据 https://github.com/alipay/sofa-rpc-boot-projects/tree/master/sofa-boot-samples/src/main/java/com/alipay/sofa/rpc/samples/direct 的例子做改造，提供方抛出异常后调用方是可以获取到异常信息的，你可以尝试一下。

**Comment by xiaowan** [comment]
测试过才提的issue，建议官方开发人员也尝试一下...

**Comment by ujjboy** [comment]
hi @xiaowan  没有感知是指捕获不到异常吗？ 可否上传一个可复现的demo工程？

**Comment by liangyuanpeng** [comment]
试了一下，服务方显示的抛出一个空指针异常以及一个自定义异常，调用放都可以捕获到，

这个问题可以再描述得详细一点

**Comment by guzhangyu** [comment]
在服务方方法没有返回值的时候会有这个问题，但是有返回值的时候不会有这个问题。

**Comment by liangyuanpeng** [comment]
@guzhangyu   有返回值跟没返回值的我都试了一下，调用方都可以捕获到异常

**Comment by guzhangyu** [comment]
git 地址:https://github.com/guzhangyu/SofaTest ,子模块SofaTest2是调用方，子模块SofaServerTest是服务方；com.unitymob.test.web.controller.SampleController里 test1 方法在远程调用出现异常后，后面的代码还会继续进行；
 test2方法，出现异常后，返回结果没有出现500。

**Comment by JervyShi** [comment]
已复现，当前实现中针对 void 类型的返回值未处理异常抛出，这个我们改下。

**Comment by liangyuanpeng** [comment]
@JervyShi 
这个问题不涉及使用使用SOFARPC方式调用吧，还是我测试的方向不对:smile:

**Comment by JervyShi** [comment]
@liangyuanpeng 如 @guzhangyu 的描述，只有声明为 void 的方法有影响，有返回值的方法不受影响。

**Comment by xiaowan** [comment]
既然这个框架是支付宝内部沉淀了这么久发布出来的，支付宝内部那么多的开发，那么多的应用场景，这个问题没有遇到过？还是内部使用跟外部开源出来的是两个不一样的版本？

**Comment by leizhiyuan** [comment]
对内之前是用 jdk 的代理.这个在开源版本里也是有的.只是开源版本为了性能考虑,切换到了 javassist 生成动态代理.
