### ISSUE TITLE
ConsistentHashLoadBalancer not support weight

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-rpc#213]

**Comment by leizhiyuan** [comment]
ConsistentHash make request whose paramter is same to router to same node, if you need support weight

maybe you can pr a new WeightConsistentHashLoadBalancer?

**Comment by 315157973** [comment]
@leizhiyuan  Can you describe the expected effect？For actual nodes with small weight, the number of virtual nodes is also relatively small.Do you want this effect?

**Comment by leizhiyuan** [comment]
if we have 5 real  nodes , weight is 1,2,3,4,5

now we have 128 virtual nodes, but after add weight support ,we can have LCM(1,2,3,4,5)*128 = 1920 nodes,

1*128 nodes are for  real node 1
2*128 nodes are for  real node 2

etc,then will choose the real node by weight and  keep consistent.

you can  caculate the lowest common multiple (L.C.M.)  if we have 2,3,6,maybe you can have LCM(2,3,6)=6*128 virtual nodes

@315157973
