### ISSUE TITLE
sofa-rpc 支持hessian4

### ISSUE THREAD

**Issue by ypyaaa** [alipay/sofa-rpc#217]
需求 sofa-rpc支持hessian4

**Comment by leizhiyuan** [comment]
支持 hessian4, 由于我们目前支持 hessian3,  hessian3和 hessian4一些类名应该是一样的,这可能会导致 hessian3和 hessian4 不能共存. hessian4<->hessian3的双向调用也可以存在兼容性问题.这个需要测试下验证下.

另外,@ypyaa 想问一下,你们这边对 hessian4的需求背景是? 能简单说下吗?

和 hessian4的比较 https://github.com/alipay/sofa-hessian/issues/6

**Comment by ypyaaa** [comment]
您好。 我们当前的技术背景是 将我们项目的老版本进行改造 老版本的项目全部都是基于hessian4来进行序列化的 我们想用sofa-rpc做传输 用老项目的hessian4来进行序列化  我看 您提供的sofa-hessian 还有sofa-rpc-all都是基于hessian3.3.0 所以提出了此个issue 我们想使用sofa 来做我们团队的中间件
现在我们碰到的问题主要是三个
1.sofa目前的例子全部是基于springboot开发的 但我们的老项目全部是SSM框架 这样导致我们适配很麻烦
2.sofa的hessian版本只有3.3.0 但我们老项目的序列化全部是hessian4 我们担心会影响我们现在的业务系统 我们要全部项目重新测试
3.我们想将注册中心从zookeeper迁移到eureka上面 我看sofa目前还不支持eureka这个注册中心 
我们目前也是在基于sofa将我们的项目进行改造 这是我们当前的大的技术背景 @leizhiyuan

**Comment by leizhiyuan** [comment]
1.sofa目前的例子全部是基于springboot开发的 但我们的老项目全部是SSM框架 这样导致我们适配很麻烦

这个问题,确实会有一些工作量.你们也可以看下迁移至 SpringBoot 的工作量来评估.

2.sofa的hessian版本只有3.3.0 但我们老项目的序列化全部是hessian4 我们担心会影响我们现在的业务系统 我们要全部项目重新测试

这个情况,实际上,我理解,你们可以将3.3.0的依赖排除.然后将 hessian4的依赖加进来即可(3和4这种方式无法并存,主要是类名的冲突).我这边没有验证过.如果你排除之后有其他问题,可以发出来,我们一起看下.

3.我们想将注册中心从zookeeper迁移到eureka上面 我看sofa目前还不支持eureka这个注册中心
我们目前也是在基于sofa将我们的项目进行改造 这是我们当前的大的技术背景

这个https://github.com/alipay/sofa-rpc/issues/52 issue 中,@liufeiit 这边在做.也在我们的规划中.如果你们要自己做eureka的支持,扩展一个注册中心即可,应该还是比较方便的.

**Comment by ypyaaa** [comment]
@leizhiyuan 
1. 请问一下 sofa不是在您那运行了很长时间 肯定会有支持原生spring项目的 为什么不考虑开源这个
2.hessian这个问题我们目前正在适配 有问题会随时和您保持沟通
3.我同事目前想问 eureka注册中心适配sofa 目前开发到哪个阶段
4.请问考虑开源sofa-mesh吗 我们前期工作都是为了兼容sofa-mesh做准备

**Comment by leizhiyuan** [comment]
1.请问一下 sofa不是在您那运行了很长时间 肯定会有支持原生spring项目的 为什么不考虑开源这个

对外我们精力目前主要还是投入在 SpringBoot 和 SOFABoot上.对 Spring 的支持.这也是我们重点支持的产品类型.

2.hessian这个问题我们目前正在适配 有问题会随时和您保持沟通

3.我同事目前想问 eureka注册中心适配sofa 目前开发到哪个阶段

这个我在另一个 issue 中跟对应同学沟通中,还没回复.

4.请问考虑开源sofa-mesh吗 我们前期工作都是为了兼容sofa-mesh做准备

mesh 会开源.大约在7月底,8月初的样子.

**Comment by ypyaaa** [comment]
我看你们 的sofa-rpc-all是集成sofa-hessian3.3.0的 里面的hessian包是去不掉的 如果强行去掉sofa-hessian3.3.0 启动sofa就会报类找不到异常 如果同时保留两个hessian版本 就会包jar包冲突 如果去除我们的hessian版本 会报hessian原生类找不到
@leizhiyuan

**Comment by leizhiyuan** [comment]
只保留你们的 hessian4 报什么错误?

**Comment by ujjboy** [comment]
BoltClientTransport 初始化的时候注册 hessian，这个看能不能优化下，判断下序列化协议再初始化。

**Comment by leizhiyuan** [comment]
我本地看了一下,主要是泛化调用那个包,还有一些就是 hessian4里面的字段访问控制变化.再就是新增的安全黑名单.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project sofa-rpc-codec-sofa-hessian: Compilation failure: Compilation failure:
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java:[19,26] cannot find symbol
[ERROR] symbol:   class ClassNameResolver
[ERROR] location: package com.alipay.hessian
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java:[20,26] cannot find symbol
[ERROR] symbol:   class NameBlackListFilter
[ERROR] location: package com.alipay.hessian
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java:[64,39] _staticTypeMap has private access in com.caucho.hessian.io.SerializerFactory
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java:[71,50] incompatible types: com.caucho.hessian.io.Deserializer cannot be converted to java.lang.Class
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java:[95,31] _cachedTypeDeserializerMap has private access in com.caucho.hessian.io.SerializerFactory
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java:[99,9] _cachedTypeDeserializerMap has private access in com.caucho.hessian.io.SerializerFactory
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java:[83,13] cannot find symbol
[ERROR] symbol:   class ClassNameResolver
[ERROR] location: class com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java:[83,46] cannot find symbol
[ERROR] symbol:   class ClassNameResolver
[ERROR] location: class com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer
[ERROR] /sofa-open/sofa-rpc-open/extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java:[84,36] cannot find symbol
[ERROR] symbol:   class NameBlackListFilter
[ERROR] location: class com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

```

**Comment by leizhiyuan** [comment]
@ypyaaa  我刚才想了下,hessian3 和 hessian4 只是代码上的差异,协议层面我理解应该是兼容的才对.

都对应的是http://hessian.caucho.com/doc/hessian-serialization.html hessian 2 protocol 的规范.

**Comment by ypyaaa** [comment]
@leizhiyuan 不行 我今天下午试了  有碰见两个问题 
1.zookeeper上面已经注册服务 但client端找不到该服务
2.本地 server使用sofa-hessian client 使用sofa4 会报反序列化异常

**Comment by leizhiyuan** [comment]
能否提供一个可复现的 demo? 我来看下.

**Comment by ypyaaa** [comment]
我们现在的 问题主要是 服务端和客户端都能正常启动 但客户端发送服务端数据的时候就会报
com.alipay.sofa.rpc.core.exception.SofaRpcException: com.alipay.remoting.rpc.exception.RpcServerException: java.lang.NoSuchFieldError: _staticTypeMap. AdditionalErrMsg: Deserialize RpcRequestCommand failed in RpcRequestProcessor, id=6, deserializeLevel=2
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.convertToRpcException(BoltClientTransport.java:372) ~[sofa-rpc-all-5.3.1.jar:5.3.1]
异常
服务端没有接收到请求
@leizhiyuan

**Comment by leizhiyuan** [comment]
这个地方就是我说的 rpc 框架要改一下的地方.

**Comment by ypyaaa** [comment]
@leizhiyuan  请问一下 改哪里？ 我们想先试试

**Comment by leizhiyuan** [comment]
com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer#getSerializerFactory

这个代码段.不考虑泛化调用.可以直接先返回
```
 return new SerializerFactory();

```

我验证的时候是通过- D 参数来走到这个逻辑的
```
  /**
     * Gets serializer factory.
     *
     * @param multipleClassLoader the multiple class loader
     * @param generic             the generic
     * @return the serializer factory
     */
    protected SerializerFactory getSerializerFactory(boolean multipleClassLoader, boolean generic) {
        if (generic) {
            return multipleClassLoader ? new GenericMultipleClassLoaderSofaSerializerFactory() :
                new GenericSingleClassLoaderSofaSerializerFactory();
        } else if ("hessian4".equals(System.getProperty("s"))) {

            return new SerializerFactory();
        } else {
            return multipleClassLoader ? new MultipleClassLoaderSofaSerializerFactory() :
                new SingleClassLoaderSofaSerializerFactory();
        }
    }
```

**Comment by ypyaaa** [comment]
@leizhiyuan sofa-rpc-all包里面的 我确实没找到这个类

**Comment by ypyaaa** [comment]
我的sofa-rpc版本是 5.3.1 里面好像没有这个包

**Comment by ypyaaa** [comment]
@leizhiyuan 新加这个验证在我们这边是过不去的("hessian4".equals(System.getProperty("s")))  这个验证在我们这边是false

**Comment by leizhiyuan** [comment]
启动加这个参数. 这是为了临时验证的.之后如果可行,我们会改成其他的配置方式

```
-Ds=hessian4
```

**Comment by gxcsoccer** [comment]
hessian 3 和 hessian 4 在 bolt 协议上如何区分？ 还是说不区分替换的关系？

**Comment by ypyaaa** [comment]
我们是想用bolt传输 序列化反序列化协议用我们老项目的hessian4
