### ISSUE TITLE
LocalRegistry notifyConsumer  has a bug

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-rpc#218]
```
   ProviderGroup innew = differentValue.rightValue();
```
shoule be 
 ```
 ProviderGroup innew = differentValue.leftValue();
```

if you start LocalBoltClientMain first,and then start LocalBoltServerMain, you can find client not find server,the reason is this bug

**Comment by leizhiyuan** [comment]
@huangyunbin Thanks! please pr your changes to  branch 5.4, we will merge it.
