### ISSUE TITLE
sofa－rpc 基于 eureka 注册中心

### ISSUE THREAD

**Issue by Lmyxny** [alipay/sofa-rpc#221]
目前，有这类想法的可以讨论下一起研究怎么实现。

**Comment by JervyShi** [comment]
@Lmyxny 可以先看下 https://github.com/alipay/sofa-rpc/issues/52#issuecomment-384541012 的建议，然后思考下接入 Eureka 的话你的设计想法。

**Comment by Lmyxny** [comment]
@JervyShi 我看到#52的问题了，自己继承registry方法实现，但是这样的实现只是基于了累，但是基于eureka的话，还是需要过多的封装。感觉特别的麻烦

**Comment by JervyShi** [comment]
@Lmyxny 这个是接入注册中心的标准方式，通过这个统一的模型纳入 SOFA RPC 的整套体系里面去。你有什么更好的建议么？

**Comment by Lmyxny** [comment]
首先，sofa－rpc 想要使用 spring boot 和 spring的工程 就需要两套不同的jar包，但是这只是注册形式不同而已，如果要想迁移注册中心到eureka上，就需要同时修改两套代码的源码，或者扩展其源码，都是及其浪费时间和人力的，我现在想放弃使用eureka做注册中心，还用原来的zk。

**Comment by JervyShi** [comment]
可以先使用 zk 的方式，Eureka 的接入也在我们的 [Roadmap](http://www.sofastack.tech/sofa-rpc/docs/RoadMap) 中，后续这些工作我们会再安排。这个 issue 先关闭了，关于 Eureka 的讨论可以继续在 #52 中讨论。
