### ISSUE TITLE
LocalRegistry use file lastModified is not rigorous

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-rpc#223]
file lastModified is only Accurate to second：
```
public static void main(String[] args) throws Exception {
		File file = new File("/tmp/1.txt");
		file.createNewFile();
		long now = System.currentTimeMillis();
		System.out.println("now:         " + now);
		file.setLastModified(now);
		System.out.println("lastModified:" + file.lastModified());
	}
```
result is 
```
now:         1530934441627
lastModified:1530934441000
```

loadBackupFileToCache method  read file but return RpcRuntimeContext.now() is also not rigorous.

**simple solution** : read file every time ,compare content is changed

**Comment by leizhiyuan** [comment]
Thanks for your advice, you can pr to the 5.4 branch, we will merge it.

**Comment by jiacheo** [comment]
You can simply use the `MD5` or `SHA` sign to check whether the file's changed.

**Comment by leizhiyuan** [comment]
use md5 to check
