### ISSUE TITLE
wiki路径配置错误

### ISSUE THREAD

**Issue by Justice-love** [alipay/sofa-rpc#226]
Sidebar中wiki路径配置错误

**Comment by ujjboy** [comment]
@Justice-love  感谢反馈，文档我们将转移到官网 http://www.sofastack.tech  后面 wiki 将关闭。

**Comment by leizhiyuan** [comment]
wiki 已经关闭.

**Comment by leizhiyuan** [comment]
http://www.sofastack.tech/sofa-rpc/docs/Home
