### ISSUE TITLE
xml配置项说明

### ISSUE THREAD

**Issue by shihaoking** [alipay/sofa-rpc#232]
希望能把rpc相关的xml配置项列出来，并说明每个配置项和属性的作用。目前只有JAVA对象的参数说明文档

**Comment by shihaoking** [comment]
比如<sofa:service>配置项有哪些可用子配置项，且个子配置项有哪些属性以及属性的作用是什么

**Comment by leizhiyuan** [comment]
xsd 中点进去就可以看到,对应的 xsd 中的注释之后补充下.

**Comment by leizhiyuan** [comment]
http://www.sofastack.tech/sofa-rpc/docs/Application-RPC-Config
http://www.sofastack.tech/sofa-rpc/docs/Configuration-Common

**Comment by leizhiyuan** [comment]
xsd 中进行完整地注释说明，不通过文档的形式。


https://github.com/alipay/sofa-boot/issues/249 会在这里进行更新。这个先关闭了。

**Comment by leizhiyuan** [comment]
@khotyn 好的。那这个就按照发布和引用，写到文档上先

**Comment by leizhiyuan** [comment]
fix in https://github.com/alipay/sofastack-doc/pull/53
