### ISSUE TITLE
sofa-rpc使用dubbo协议 version 问题

### ISSUE THREAD

**Issue by dongxiaoxiong** [alipay/sofa-rpc#238]
sofa-rpc使用dubbo协议，不能设置dubbo ServiceBean.version
可否通过sofa-rpc ProviderConfig.uniqueId 的值设置到 ServiceBean.version?

Environment
SOFARPC version:2.3.2
JVM version (e.g. java -version):1.8.0
OS version (e.g. uname -a): Darwin
Maven version:3.3.9
IDE version: IntelliJ IDEA

**Comment by leizhiyuan** [comment]
com.alipay.sofa.rpc.bootstrap.dubbo.DubboProviderBootstrap#copyProvider
com.alipay.sofa.rpc.bootstrap.dubbo.DubboConsumerBootstrap#copyConsumer
目前转换的时候是直接设置了1.0,这里可以用对应 config 的 uniqId 来设置.
有兴趣可以提个 pr. 改一下这里.
