### ISSUE TITLE
Change Map.keySet to Map.entrySet 

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-rpc#252]
### Describe the bug

In order to support compile in jdk8， but run in jdk6，we need to change code which
use keySet to entrySet

because keySet compiled in jdk8.

java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet() 
Ljava/util/concurrent/ConcurrentHashMap$KeySetView;

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by liangyuanpeng** [comment]
@leizhiyuan 
the reason why that happens is you get the KeySetView in ``ConcurrentHashMap#keySet``

and 
```
 * @since 1.8
     */
    public static class KeySetView<K,V> extends CollectionView<K,V,K>
```
and i looksome code like
```
 providerInfos.addAll(aliveConnections.keySet());
            providerInfos.addAll(subHealthConnections.keySet());
            providerInfos.addAll(retryConnections.keySet());
```

is unnecessary to use entrySet


you can replace a  ConcurrentMap with a ConcurrentHashMap

such as some code in `AllConnectConnectionHolder`
```
 protected ConcurrentHashMap<ProviderInfo, ClientTransport> uninitializedConnections = new ConcurrentHashMap<ProviderInfo, ClientTransport>();
```
replace  to

```
 protected ConcurrentMap<ProviderInfo, ClientTransport> uninitializedConnections = new ConcurrentHashMap<ProviderInfo, ClientTransport>();
```

**Comment by leizhiyuan** [comment]
@liangyuanpeng Thanks for your advice.
