### ISSUE TITLE
Change all confreg to registry.

### ISSUE THREAD

**Issue by JervyShi** [alipay/sofa-rpc#253]
### Describe the bug

`Confreg` is not well known to the public，What we want say is `Registry`.

Should replace all `CONFREG` to `REGISTRY` in the code.

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by liangyuanpeng** [comment]
some code like that ?
```
rpc_register_confreg_ignore
```
change to
```
rpc_register_registry_ignore
```

**Comment by JervyShi** [comment]
@liangyuanpeng Yes, also the key definition like `INFO_CONFREG_IGNORE` can be changed to `INFO_REGISTRY_IGNORE`,  `CONFIG_RPC_REGISTER_CONFREG_IGNORE` can be changed to `CONFIG_RPC_REGISTER_REGISTRY_IGNORE`.
