### ISSUE TITLE
Support OpenTracing base on sofa-tracer.

### ISSUE THREAD

**Issue by ujjboy** [alipay/sofa-rpc#26]
See more at http://opentracing.io/  and https://github.com/alipay/sofa-tracer

**Comment by liangyuanpeng** [comment]
https://github.com/alipay/sofa-tracer  404

**Comment by leizhiyuan** [comment]
@liangyuanpeng  will be accessible soon, please wait.

**Comment by billowqiu** [comment]
still 404

**Comment by billowqiu** [comment]
可以访问了
