### ISSUE TITLE
怎么实现图片上传功能？

### ISSUE THREAD

**Issue by davis1214** [alipay/sofa-rpc#262]
### Your question
图片上传时，rcp-config.json 中配置的serialize.blacklist.enable 参数无效。且通过配置系统变量方式，也无效。

### Your scenes
如下找到的系统代码

```
public class ClassNameResolverBuilder {

    /**
     * Build default ClassNameResolver
     * 
     * @return Default ClassNameResolver
     */
    public static ClassNameResolver buildDefault() {
        String enable = System.getProperty("serialize.blacklist.enable", "true");
        if (Boolean.TRUE.toString().equalsIgnoreCase(enable)) {
            ClassNameResolver resolver = new ClassNameResolver();
            resolver.addFilter(new InternalNameBlackListFilter());
            return resolver;
        }
        return null;
    }
}
```
### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 5.4.3
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):  Darwin
- Maven version: 3.X
- IDE version: 18

**Comment by davis1214** [comment]
图片上传没有找到好的方式实现。后来通过byte数组方式实现普通图片的上传

**Comment by leizhiyuan** [comment]
图片上传不是 rpc 的一个推荐的使用场景,因为数据一般非常大,对正常的 rpc 请求可能有性能影响,内部对于这种情况,我们也是推荐用户自己先读取成 byte 数组,再进行传递的.
