### ISSUE TITLE
泛型调用提示“ 没有获得服务[]的调用地址，请检查服务是否已经推送”

### ISSUE THREAD

**Issue by liwooood** [alipay/sofa-rpc#263]
如果是代码export的服务，泛型调用是可以的，但如果是xml配置的，泛型调用就提示 没有获得服务[com.alipay.sofa.boot.examples.demo.rpc.bean.PersonService:1.0]的调用地址，请检查服务是否已经推送 

运行里边的单元测试就可以了。

- SOFARPC version:5.4.3
[xml-server.zip](https://github.com/alipay/sofa-rpc/files/2286177/xml-server.zip)

- JVM version (e.g. `java -version`):1.8.0_131
- OS version (e.g. `uname -a`):windows10
- Maven version:3.3.9
- IDE version:idea

**Comment by khotyn** [comment]
application.properties 这个配置文件中的 SOFARPC 的 Registry 配置的 Key 错了，改成：

```
com.alipay.sofa.rpc.registry.address=zookeeper://127.0.0.1:2181
```

就可以了。
