### ISSUE TITLE
filter拦截器@AutoActive问题

### ISSUE THREAD

**Issue by FzNl** [alipay/sofa-rpc#271]
### Your question
- @AutoActive(providerSide = true, consumerSide = true)
只有providerSide生效进行拦截；
- 新增另一个拦截类
@AutoActive(consumerSide = true)
consumerSide生效

### Environment

- SOFARPC version: 5.4.3；SOFA-BOOT version:2.4.3
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:3.2.5
- IDE version:

**Comment by ujjboy** [comment]
Thanks, It's a bug.

https://github.com/alipay/sofa-rpc/blob/1ba6e13e87cae24c5b1b8be3fe37252af907b342/core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java#L83-L87

should be 
```java
if (autoActive.providerSide()) { 
     PROVIDER_AUTO_ACTIVES.put(alias, extensionClass); 
}
if (autoActive.consumerSide()) { 
     CONSUMER_AUTO_ACTIVES.put(alias, extensionClass); 
 } 
```

some bug  as:

https://github.com/alipay/sofa-rpc/blob/1ba6e13e87cae24c5b1b8be3fe37252af907b342/core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java#L79-L83

**Comment by ujjboy** [comment]
@FzNl  Can you fix it and create a PR?

**Comment by FzNl** [comment]
ok
