### ISSUE TITLE
ExtensionLoader print exception

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-rpc#278]
### Your question

com.alipay.sofa.rpc.ext.ExtensionLoader#readLine

```
try {
            tmp = ClassUtils.forName(className, false);
        } catch (Throwable e) {
            if (LOGGER.isWarnEnabled()) {
                LOGGER.warn("Extension {} of extensible {} is disabled, cause by: {}",
                    className, interfaceName, ExceptionUtils.toShortString(e, 2));
            }
            return;
        }
```
### Your scenes

describe your use scenes (why need this feature)

### Your advice

maybe we don't need to catch Throwable?

or we can print ExceptionUtils.toString(e)?

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
The question is we don't know why user don't import classes.

For example:
`Registry` has three extensions: zookeeper, dsr, consul 

If user want use zookeeper as registry, and did not import `dsr.jar` and `consul.jar`, dsr and consul registry extension will disabled, we need ignore it.

But if user did not import `zookeeper.jar`, zookeeper registry will disabled, too. It's better to throw exception when not found extension ( get registry from `RegistryFactory`).

**Comment by ujjboy** [comment]
Now, these three factory did not throw exception when not found extension:
 `CompressorFactory`, `SerializerFactory`, `ProtocolFactory`。

**Comment by ujjboy** [comment]
At ExtensionLoader#readLine, we can add extra DEBUG exception stack trace.
