### ISSUE TITLE
org.apache.httpcomponents.httpmime 4.4.9版本在maven仓库不存在，但是bom中写的是该版本

### ISSUE THREAD

**Issue by zhaojigang** [alipay/sofa-rpc#292]
hi，org.apache.httpcomponents.httpmime 4.4.9版本在maven仓库不存在，但是bom中写的是该版本，是不是需要换个版本呢？
sofa-rpc版本：5.5.0-SNAPSHOT

**Comment by ujjboy** [comment]
@zhaojigang Of course, could you fix it and submit a PR?

**Comment by zhaojigang** [comment]
ok, it's my pleasure!
