### ISSUE TITLE
服务切面不起作用

### ISSUE THREAD

**Issue by dickensma** [alipay/sofa-rpc#317]
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dickensma** [comment]
在service的方法上添加自定义注解，通过配置切面注解的方式来拦截，发现不起作用，单元测试是可以起作用，原因大致可能是：spring bean 是用的cglib作为代理的，但是直接反射用的可能是asm

**Comment by ujjboy** [comment]
@dickensma 可以提供一个复现demo吗？    

在RPC的逻辑里，应该只关心设置进来的 ref 对应的实现对象。不管这个实现对象是普通的实现类的Bean还是这个Bean的AOP的代理类，RPC都是直接调用的。

**Comment by dickensma** [comment]
ProviderConfig 的setBean 注入 spring的代理对象切面才可以起作用
