### ISSUE TITLE
sofa-rpc 5.4.5版本是否支持consul注册中心

### ISSUE THREAD

**Issue by wangxiaotao00** [alipay/sofa-rpc#319]
### Your question

sofa-rpc 5.4.5版本是否支持consul注册中心

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
不支持，这个在5.5.0里程碑里
