### ISSUE TITLE
我可以贡献etcd注册中心代码，依赖jdk8，是否支持？

### ISSUE THREAD

**Issue by zonghaishang** [alipay/sofa-rpc#32]
我可以贡献etcd注册中心代码，但是必须jdk8，是否支持？

**Comment by zonghaishang** [comment]
@khotyn
good, 因为etcd目前只有唯一jdk8实现的jetcd支持v3， 所以etcd注册中心我也就用jdk8了，很高兴看到你们开源， 我会看下框架接口做一次改造， 或许将来dubbo没有强制兼容jdk7，我也会贡献出去

**Comment by ujjboy** [comment]
@zonghaishang  SOFARPC 编译出来的 target.version 必须是 1.6 的。 因为 SOFARPC 是整个蚂蚁金服都在使用的，我们必须兼容JDK6的使用场景。当然，如果要使用`jetcd`这个扩展，可以要求使用者必须JDK8及以上。

**Comment by ujjboy** [comment]
Duplicate #153. 

@zonghaishang 另外一位同学已认领任务，我先关闭此Issue，如有其它问题再Reopen。

**Comment by zonghaishang** [comment]
好的，这段时间比较忙，dubbo的etcd3基于jetcd开发完成了，欢迎开发etcd注册中心的同学互相交流

在 2018年6月4日，19:55，Geng Zhang <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #32<https://github.com/alipay/sofa-rpc/issues/32>.
