### ISSUE TITLE
sofa-rpc是否支持服务治理？

### ISSUE THREAD

**Issue by litttlefisher** [alipay/sofa-rpc#322]
### Your question
sofa-rpc是否支持服务治理？类似于dubbo的管理台的？亦或者说有一个类似于spring boot admin的服务监控平台？

**Comment by JervyShi** [comment]
目前还没有服务端，SOFA RPC 的服务治理能力是可扩展的，如有强烈需求欢迎共建。

**Comment by SteNicholas** [comment]
@JervyShi 能提供服务治理能力吗？因为像优雅停机暴露接口提供给发布提供最好通过服务治理吧，点评的Pigeon就是这么实现的

**Comment by JervyShi** [comment]
@SteNicholas 目前 Zookeeper 作为服务注册中心的实现中，是有留出接口配置与IP级别配置的下发渠道的，服务治理能力目前开源版缺一个管控台来做配置的管理，这部分有兴趣是可以共建的。
https://github.com/alipay/sofa-rpc/blob/68f2519a471405cd3ea382cb89a287796dc7bb5c/extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java#L78-L82

**Comment by sohoku** [comment]
@JervyShi 你好，我目前正在实验使用已有扩展点获取到sofarpc内部的一些连接情况，但是收到了一下报错，是不是我使用错了？
ConnectionHolder all = ExtensionLoaderFactory.getExtensionLoader(ConnectionHolder.class).getExtension("all");

![image](https://user-images.githubusercontent.com/5020217/48190688-4ce10580-e37e-11e8-91fa-ed953c1e021e.png)

**Comment by JervyShi** [comment]
@sohoku 这个问题单独开一个 Issue 单独讨论吧

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/issues/369 will develop soon
