### ISSUE TITLE
RPC-02306: 没有获得服务问题

### ISSUE THREAD

**Issue by rayzeng** [alipay/sofa-rpc#323]
### Describe the bug

单个consumer，单个provider，使用注解的方式提供和调用bolt接口，zookeeper注册中心；
当两个服务同时启动时，会偶现调用返回：RPC-02306: 没有获得服务；
单步跟发现在SingleGroupAddressHolder里registryGroup里providerInfos为空，正常情况下providerInfos会有值的；
此时provider端服务是正常注册上去的，用Test可以正常调用，怀疑缓存在内存的provider信息有问题，增加到缓存的时候provider可能还没初始化成功；
重启consumer或provider都可以正常调用

### Environment

- SOFARPC version: 5.4.5
- JVM version (e.g. `java -version`):1.8

**Comment by ujjboy** [comment]
@rayzeng  先试下 5.4.6.

**Comment by rayzeng** [comment]
升级后暂时没有重现
