### ISSUE TITLE
TtlScheduler如何保证启动一次？

### ISSUE THREAD

**Issue by mikefreemanNice** [alipay/sofa-rpc#325]
### Your question
```
com.alipay.sofa.rpc.registry.consul.internal.ConsulManager#ConsulManager
```
这里的ConsulManager的host和port应该是consul的服务，应该是固定的，那么是不是每发布一个服务，就会有一个新的ttlScheduler启动。是不是造成定时任务启动多了

**Comment by leizhiyuan** [comment]
@NeGnail  master 代码上帮看看,这个是不是可以做成单例.

**Comment by NeGnail** [comment]
@mikefreemanNice   com.alipay.sofa.rpc.registry.consul.ConsulRegistry#init  这个方法保证了只会有一个consulManager实例。

**Comment by leizhiyuan** [comment]
没有问题先关闭了.
