### ISSUE TITLE
动态绑定DynamicFeature未生效

### ISSUE THREAD

**Issue by rayzeng** [alipay/sofa-rpc#332]
Your question
在DynamicFeature接口实现类加上@Provider注解 ，但启动时未调用DynamicFeature接口的configure方法。
@Provider
@ConstrainedTo(RuntimeType.SERVER)
public class ApiMetricsFeature implements DynamicFeature

在DynamicFeature实现类初始化之后， 实现InitializingBean接口，在afterPropertiesSet调用JAXRSProviderManager.registerCustomProviderInstance(this)也未触发调用configure

单步跟DynamicFeature实现类初始化在registerProvider之后才调用到，系统已经初始化完Provider，此时再registerCustomProviderInstance实际并没有效果，求解

Environment
Starter version:2.5.0
JVM version (e.g. java -version):1.8

**Comment by ujjboy** [comment]
能提供个重现的demo吗？
