### ISSUE TITLE
session超时后无法重连zk

### ISSUE THREAD

**Issue by sohoku** [alipay/sofa-rpc#334]
zk session在60分钟超时后，无法重连
主动重启zkServer时是可以重连的，应用重启也是可以连上的
zk3.4.13,sofarpc5.4.6
com:
  alipay:
    sofa:
      rpc:
        registry-address: zookeeper://172.168.5.30:2181
        bolt-port: 12208
        bolt-thread-pool-core-size: 50
        bolt-thread-pool-max-size: 1000
        bolt-thread-pool-queue-size: 20000
        bolt-accepts-size: 500
        #        virtual-host: 172.17.5.200
        virtual-port: 12228

        aft-time-window: 20
        aft-least-window-count: 30
        aft-least-window-exception-rate-multiple: 6
        aft-regulation-effective: true
        aft-degrade-effective: true
        aft-weight-degrade-rate: 0.5
        aft-weight-recover-rate: 1.2
        aft-degrade-least-weight: 1
        aft-degrade-max-ip-count: 2

    compile ('org.apache.zookeeper:zookeeper:3.4.13')
    compile 'org.apache.curator:curator-framework:2.12.0'
    compile 'org.apache.curator:curator-recipes:2.12.0'

20181016 20:39:06.414 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Unable to read additional data from server sessionid 0x103d294400c0020, likely server has closed socket, closing socket connection a
nd attempting reconnect
20181016 20:39:06.517 [main-EventThread] o.a.c.f.s.ConnectionStateManager -State change: SUSPENDED
20181016 20:39:10.906 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Opening socket connection to server chess_t01/172.16.184.214:2181. Will not attempt to authenticate using SASL (unknown error)
20181016 20:39:10.906 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Socket connection established to chess_t01/172.16.184.214:2181, initiating session
20181016 20:39:10.915 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Unable to reconnect to ZooKeeper service, session 0x103d294400c0020 has expired
20181016 20:39:10.915 [main-EventThread] o.a.c.f.s.ConnectionStateManager -State change: LOST
20181016 20:39:10.915 [main-EventThread] o.a.c.ConnectionState -Session expired event received
20181016 20:39:10.915 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Unable to reconnect to ZooKeeper service, session 0x103d294400c0020 has expired, closing socket connection
20181016 20:39:12.102 [main-EventThread] o.a.z.ZooKeeper -Initiating client connection, connectString=172.16.184.214:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@52bef30b
20181016 20:39:12.102 [main-EventThread] o.a.z.ClientCnxn -EventThread shut down for session: 0x103d294400c0020
20181016 20:39:14.740 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Opening socket connection to server chess_t01/172.16.184.214:2181. Will not attempt to authenticate using SASL (unknown error)
20181016 20:39:14.740 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Socket connection established to chess_t01/172.16.184.214:2181, initiating session
20181016 20:39:14.743 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Session establishment complete on server chess_t01/172.16.184.214:2181, sessionid = 0x103d294400c0024, negotiated timeout = 40000
20181016 20:39:14.755 [main-EventThread] o.a.c.f.s.ConnectionStateManager -State change: RECONNECTED

Tks.

**Comment by sohoku** [comment]
![qq 20181017141903](https://user-images.githubusercontent.com/5020217/47066054-87d89900-d217-11e8-8321-4312fdc81c01.png)
正在对应用进行压测时，发现与zk的连接断了，出现了time_wait

**Comment by sohoku** [comment]
20181017 17:50:47.643 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Client session timed out, have not heard from server in 28224ms for sessionid 0x103d294400c0053
20181017 17:53:16.814 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Client session timed out, have not heard from server in 28224ms for sessionid 0x103d294400c0053, closing socket connection and attempting reconnect
20181017 17:53:46.772 [main-SendThread(chess_t01:2181)] o.a.z.s.ZooKeeperThread -Exception occurred from thread main-SendThread(chess_t01:2181)
java.lang.OutOfMemoryError: GC overhead limit exceeded
20181017 17:53:49.108 [main-EventThread] o.a.c.f.s.ConnectionStateManager -State change: SUSPENDED

**Comment by khotyn** [comment]
@leizhiyuan

**Comment by leizhiyuan** [comment]
我看你描述是说：zk session在60分钟超时后，无法重连

意思是说如果我本地起了进程，然后进程持续60分钟一直运行，然后和 zk 的 session 会断开是这样么？
主要是想看下怎么复现。

**Comment by sohoku** [comment]
是的，贴一张没有gc，且把session超时时间改短后出现的图
![qq 20181017183151](https://user-images.githubusercontent.com/5020217/47080553-e2372100-d23a-11e8-9c27-42303897fdd0.png)

**Comment by leizhiyuan** [comment]
@sohoku 你这边调整 session 超时是怎么调整的？能否发一下。我这边本地来验证下。

**Comment by sohoku** [comment]
修改resources/sofa-rpc/rpc-config.json
{
  // 加载顺序，越大越后加载
  "rpc.config.order": 10,
  "consumer.loadBalancer": "localPref",
  "registry.connect.timeout": 100,
  //注册中心心跳发送间隔
  "registry.heartbeat.period": 10,
  //注册中心重建连接的间隔
  "registry.reconnect.period": 10
}
这个配置在没有压测过程中是正常的

**Comment by sohoku** [comment]
虽然设置了100的超时时间，但是ClineCnxn还是将超时时间设置为了4000，日志如下：

**Comment by sohoku** [comment]
20181017 18:28:56.994 [main] o.a.z.ZooKeeper -Initiating client connection, connectString=172.16.184.214:2181 sessionTimeout=300 watcher=org.apache.curator.ConnectionState@5a98983b
20181017 18:28:57.068 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Socket connection established to chess_t01/172.16.184.214:2181, initiating session
20181017 18:28:57.076 [main-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Session establishment complete on server chess_t01/172.16.184.214:2181, sessionid = 0x103d294400c0056, negotiated timeout = 4000

**Comment by leizhiyuan** [comment]
@sohoku 好的，我先尝试复现下。我总结下

在正常情况下，你的应用是没有任何问题的
在压测场景下，如果量很大。一段时间后，客户端和 zk 的连接会断开。（但是服务端是没问题的。） 并且不会重连。

这里是客户端和 zk 连接断开还是服务端和 zk 链接断开了？

**Comment by sohoku** [comment]
是服务端与zk断开

**Comment by leizhiyuan** [comment]
@sohoku 好的，我觉得 gc 的可能是比较大的原因。如果你的服务端代码和压测项目方便的话明天看看能否发一下。我先自己本地尝试模拟下。

**Comment by sohoku** [comment]
刚好又出现了，此时cpu占用350%，mem占用12%，过30s左右，cpu占用降到了40%，服务挂在那里了
20181017 18:46:50.204 [Curator-Framework-0] o.a.z.ZooKeeper -Session: 0x103d294400c0056 closed
20181017 18:46:50.205 [Curator-Framework-0] o.a.z.ZooKeeper -Initiating client connection, connectString=172.16.184.214:2181 sessionTimeout=300 watcher=org.apache.curator.ConnectionState@5a98983b
20181017 18:46:50.205 [main-EventThread] o.a.z.ClientCnxn -EventThread shut down for session: 0x103d294400c0056
20181017 18:46:50.209 [Curator-Framework-0-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Opening socket connection to server chess_t01/172.16.184.214:2181. Will not attempt to authenticate using SASL (unkno
wn error)
20181017 18:46:50.210 [Curator-Framework-0-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Socket connection established to chess_t01/172.16.184.214:2181, initiating session
20181017 18:46:50.216 [Curator-PathChildrenCache-0] o.a.c.ConnectionState -Connection timed out for connection string (172.16.184.214:2181) and timeout (100) / elapsed (232)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:195)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:821)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:505)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:187)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:504)
        at org.apache.curator.framework.recipes.cache.RefreshOperation.invoke(RefreshOperation.java:35)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:766)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20181017 18:46:50.218 [Curator-Framework-0] o.a.c.ConnectionState -Connection timed out for connection string (172.16.184.214:2181) and timeout (100) / elapsed (244)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:195)
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87)
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:821)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:807)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:63)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
20181017 18:46:50.300 [Curator-Framework-0-SendThread(chess_t01:2181)] o.a.z.ClientCnxn -Session establishment complete on server chess_t01/172.16.184.214:2181, sessionid = 0x103d294400c0057, negotiated tim
eout = 4000
20181017 18:46:50.300 [Curator-Framework-0-EventThread] o.a.c.f.s.ConnectionStateManager -State change: RECONNECTED

**Comment by leizhiyuan** [comment]
20181017 18:46:50.300 [Curator-Framework-0-EventThread] o.a.c.f.s.ConnectionStateManager -State change: RECONNECTED


我看你这个截图重连是成功了？

是说重连间隔不符合预期？

**Comment by leizhiyuan** [comment]
@sohoku 我们分析了一下，是因为我们对于 zk 写了临时节点，这样的情况下，如果出现了断连，zk 就会删除这个节点的数据，因此， 我们再重连之后，需要进行 republish 。这个5.4.7 fix

**Comment by sohoku** [comment]
@leizhiyuan 确实如您所说，在reconnected后检查到端口连接情况，发现服务端确实是连接成功了的，只是无法调用到了，那么请问在5.4.7fix之前，哪个版本是可用的？

**Comment by leizhiyuan** [comment]
@sohoku 这个场景有 bug。如果断连后，不会主动发布再次发布和订阅。https://github.com/alipay/sofa-rpc/pull/337 这个改动已经提交了。

**Comment by leizhiyuan** [comment]
@sohoku 好的。这个发布之后，我会在这里更新。感谢~

**Comment by leizhiyuan** [comment]
已发布
