### ISSUE TITLE
SofaRequest 可否使用对象池进行复用？

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-rpc#335]
### Your question

SofaRequest 可否使用对象池进行复用？

describe your question clearly

如题，是否可以借鉴 Netty 中的对象池概念，在 ThreadLocal 中回收对象，减少 GC，提高性能？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
这个对象每个都是不一样的。复用意义不大，改下序列化成字节那里，复用字节效果应该会更明显。另外这个要分析下内存 dump，看下哪些对象占用内存过大，不符合预期的。
