### ISSUE TITLE
Question: the usage of Compressor api in sofa-rpc

### ISSUE THREAD

**Issue by whanice** [alipay/sofa-rpc#35]
I want to know the purpose of designing this interface (Compressor) ? Or solve the problem?
Such as rpc bad performace in large data scene.

**Comment by ujjboy** [comment]
Yes, if the network of RPC is really poor (like cross-country, use VPN, use network leases),  the performance bottleneck will be at the network level.  We can sacrifice more CPU load (Compressor need more CPU) in exchange for faster network latency.

**Comment by whanice** [comment]
@ujjboy  what do you think about integrated into bolt with compressor, I'm not sure whether compression can lead to performance improvements

**Comment by ujjboy** [comment]
@whanice You can see my answer above at 2nd post.

**Comment by whanice** [comment]
@ujjboy thanks for your reply.  I will try.
