### ISSUE TITLE
sofarpc使用中遇到的问题

### ISSUE THREAD

**Issue by liurui111** [alipay/sofa-rpc#351]
1. 使用hessian做序列化时，遇到LocalDateTime类型的字段，会出现栈溢出
2. 我自己实现了一个JsonSerializer ,发现BoltClientProxyInvoker类中parseSerializeType方法中，指定了只有serialization只能有hessian/protobuf/java三种，我新创建的json类型的无法加入，只有将JsonSerializer的Extension code 指定为这固定三种类型的响应code才能正常工作

sofaboot 版本为 2.5.1

**Comment by ujjboy** [comment]
1. 可以给个简单的复现demo吗？
2. 这个问题可以先将试试将 rpc的版本指定为 5.5.0-SNAPSHOT，这段逻辑在此版本已改掉。

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-hessian/issues/16

**Comment by liurui111** [comment]
感谢回答

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-hessian/pull/17 提了一个 mr, 预期下周 review 没有问题会合并.

**Comment by leizhiyuan** [comment]
@shen0834 3.3.4-SNAPSHOT 你可以先手动指定这个 hessian 版本.现在只发了 snapshot, 还没有正式发布.
