### ISSUE TITLE
SofaRouteException :RPC-02306

### ISSUE THREAD

**Issue by jewin** [alipay/sofa-rpc#354]
### BUG描述
生产环境使用一周后，调用服务端失败，错误信息为没有获得服务xxx的地址，请检查服务是否推送。注册中心使用的是zk。

### 
目前通过重启客户端应用，该问题得到解决，但是生产环境无法使用这种手段来保证稳定性，可以提供一个修复该问题的思路或者方向吗。

- SOFARPC version:5.4.3
- JVM version (e.g. `java -version`):java8
- OS version (e.g. `uname -a`):linux
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/issues/328 这个问题已经在5.4.7 中修复.麻烦这边升级一下看看.
