### ISSUE TITLE
sofa-rpc有多机房集群感知、集群容灾切换能力吗？

### ISSUE THREAD

**Issue by longXboy** [alipay/sofa-rpc#36]
可以像spring cloud里的ribbon或者istio里的envoyproxy那样设置多个机房集群(region-zone-cluster)，然后单个集群不可用了之后自动切换吗？如果有的话，内部是怎么实现的呢？

**Comment by ujjboy** [comment]
目前开源版本没有这样的实现，但是想实现这样的功能非常易于扩展。 
- Registry扩展：订阅多组配置。
- AddressHolder 扩展： 保存订阅回来的多组集群节点。
- Router扩展：默认选择当前集群，如果当前集群不可用，选择其它集群。

**Comment by longXboy** [comment]
谢谢，了解了！

**Comment by leizhiyuan** [comment]
问题咨询已解决, 先关闭了,有疑问可以再打开.
