### ISSUE TITLE
sofa的容错模块（客户端剔除）问题

### ISSUE THREAD

**Issue by fan2008shuai** [alipay/sofa-rpc#365]
发现sofa在进行服务降级时，默认配置的降级数量是2。
1. 请问是基于什么原因配置的该默认值？服务的实例数差异化较大，该默认值是否存在不合理性？
2. 如果要求接入AFT（Adaptive Fault Tolerance）模块的业务方配置阈值，是不是有接入成本的考量？
3. 如果将默认配置使用降级比例（已降级实例数与服务实例数的比值）实现，服务的实例数如何获取？服务如果进行了扩容、缩容、被从注册中心摘掉，服务的实例数处于动态变化的状态，基于何种算法计算服务的容量？依赖发布系统之类的工具获取服务容量，感觉实现上不优雅。

**Comment by JervyShi** [comment]
@fan2008shuai 1. 你指的具体是哪个配置？

**Comment by fan2008shuai** [comment]
“建议是在有单机故障的场景时，接入AFT”
（1）蚂蚁内部没有将AFT作为默认接入的模块吗？
（2）大多数的业务方应该是需要客户端单机故障剔除的吧？如果大多数业务方有接入AFT模块的需求，各自调节参数，接入成本略高。
（3）有没有考虑过不设置降级实例的阈值？如果80%实例出现问题降级之后，20%的健康实例抗所有流量，会进入降级模式，由于基于权重做路由，都降级相当于没有降级。

**Comment by NeGnail** [comment]
1）暂时没有默认接入。
2）接入时候除开关参数等简单参数外，使用默认值就可以了，这样其实是没有成本的。参数调节更多是为了提供给有更多需求的用户和业务场景使用的，是一种优化手段，不是接入必须的。当然我们也在寻找一些通用的参数配置，可以让用户不用自己进行理解而获得更优的配置。
3）如果不设置降级实例的阈值，会导致健康节点数量越来越少，负载越来越高。 这里你说的由于基于权重做路由，都降级相当于没有降级。这个可以举个例子说明一下吗，我有些没太理解。

**Comment by fan2008shuai** [comment]
@NeGnail  
不设置降级实例的阈值，假设已经有80%的实例由于不健康因素被降级权重为1（一个比较小的权重），剩下20%的实例，负载越来越高，可能会有报错或者超时的情况，此时进入AFT模块的统计，也有降级的可能。如果这20%的实例，也被不幸的降级权重为1，相当于100%的实例权重都为1，根据权重路由策略，会同等对待。例子可能有些极端，只是为了说明，是不是可以不设置降级实例的阈值。

**Comment by NeGnail** [comment]
@fan2008shuai   是的，极端情况下这样的情况是存在的。这也就是需要降级数量阈值来对降级的机器数量进行限制的原因之一。 
不过实际情况下并不会严重到100%的实例都被降级到权重1，因为当集群中越来越多机器的故障率升高的时候，整个集群的平均故障率也就随着升高，而AFT是以平均故障率作为节点是否健康的判断基准，因此这个时候很多节点虽然故障率升高，但是并不会被降级掉。     
另外，我们对节点有权重恢复机制，如果一个节点恢复健康，它的权重是会逐渐升高到初始值的。

**Comment by leizhiyuan** [comment]
如果还有欢迎,可以再打开讨论.
