### ISSUE TITLE
sofa-rpc管理及服务提供动态下线

### ISSUE THREAD

**Issue by Ale115** [alipay/sofa-rpc#366]
Hello，有俩个问题想咨询下：
  1，sofa-rpc 有无类似dubbo-admin此类后台管理程序？
  2，如果我想在部署更新A服务器的服务提供应用时，如何从注册中心踢掉A服务器应用注册？
谢谢

**Comment by JervyShi** [comment]
1. 目前暂时还没有类似 dubbo-admin 的后台，有强诉求的话欢迎共建 ^_^。
2. 应用进程关闭时（非 `kill -9` 场景下）会主动触发服务的注销，所以部署时不需要在额外踢掉这台应用的注册。

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/issues/369  will develop soon
