### ISSUE TITLE
无法为重载的方法配置不同的黑白名单

### ISSUE THREAD

**Issue by zhaojigang** [alipay/sofa-rpc#372]
![image](https://user-images.githubusercontent.com/14085645/48967705-c2f09800-f01f-11e8-925e-085a00e8eebb.png)

假设有如下接口
A {
    sayHello();
    sayHello(String name);
}

此时无法做到为sayHello()配置白名单，为sayHello(String name)设置黑名单

还是说此处使用姿势有误

**Comment by ujjboy** [comment]
**不建议使用方法重载。**
一个是接口+方法名最好是唯一的，给用户明确的用法。
另外好处就是下发动态配置的时候，能够更好通过方法名直接定位到方法，而不需要额外的传参数反射等。

**Comment by zhaojigang** [comment]
嗯，重载确实不好，我是看到这段代码，突然想到了这个问题，我 close 掉了
