### ISSUE TITLE
Exception message is not exactly

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#374]
### Describe the bug

In `FilterInvoker` ,according to the context   `"Next filter or invoker is null!"` should be `"Next filter and invoker is null!"`

```
   @Override
    public SofaResponse invoke(SofaRequest request) throws SofaRpcException {
        if (nextFilter == null && invoker == null) {
            throw new SofaRpcException(RpcErrorType.SERVER_FILTER, "Next filter or invoker is null!");
        }
        return nextFilter == null ?
            invoker.invoke(request) :
            nextFilter.invoke(invoker, request);
    }

```

### Environment

- SOFARPC version: 5.4.7
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
@OrezzerO Would you like to send a PR to fix this problem? We are extremely welcome your PR. 😆

**Comment by OrezzerO** [comment]
@khotyn  OK,I will try it.

**Comment by leizhiyuan** [comment]
we need to release 5.4.8 this week。
