### ISSUE TITLE
自定义 filter 对于 rest 协议不起作用

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#376]
### Describe the bug

自定义 filter 对于 rest 协议不起作用

 RestServer 180 行: 

```java
  @Override
    public void registerProcessor(ProviderConfig providerConfig, Invoker instance) {
        if (!isStarted()) {
            start();
        }
        // 在httpserver中注册此jaxrs服务
        if (LOGGER.isInfoEnabled()) {
            LOGGER.info("Register jaxrs service to base url http://" + serverConfig.getHost() + ":"
                + serverConfig.getPort() + serverConfig.getContextPath());
        }
        try {
            httpServer.getDeployment().getRegistry()
                .addResourceFactory(new SofaResourceFactory(providerConfig), serverConfig.getContextPath());

            invokerCnt.incrementAndGet();
        } catch (Exception e) {
            LOGGER.error("Register jaxrs service error", e);
        }
    }
```

参数 `Invoker instance` 没有用到,导致 invoker 外面包的 filterChain 没有用到.
SofaResourceFactory 中:

```java
public SofaResourceFactory(ProviderConfig providerConfig) {
        super(providerConfig.getRef());
        this.providerConfig = providerConfig;
        // 缓存服务名计算和应用名计算
        this.serviceName = ConfigUniqueNameGenerator.getServiceName(providerConfig);
        this.appName = providerConfig.getAppName();
    }
```
应该新建一个代理来替代`providerConfig.getRef()`

### Environment

- SOFARPC version:5.4.7
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@OrezzerO  
rest协议属于包装resteasy的，filter需要用jaxrs自带的的filter，看下JAXRSProviderManager类

**Comment by OrezzerO** [comment]
@ujjboy 这样子的话自定义 filter 行为对于不同协议就不一致了,使用自定义 filter 的时候很容易出问题,是否有办法让自定义 filter 的行为保持一致

**Comment by OrezzerO** [comment]
@ujjboy 我在本地修复了,稍后提个 PR

**Comment by khotyn** [comment]
@OrezzerO 👍

**Comment by leizhiyuan** [comment]
pr 可以基于5.4分支提交。5.4.8是最近的一个发布

**Comment by OrezzerO** [comment]
@leizhiyuan  有具体冲突的 case 吗, 不是很能理解冲突的意思.或者说我的问题是: resteasy 的 filter 和 sofarpc 的 filter 共存会发生什么不好的事情?

**Comment by leizhiyuan** [comment]
@ujjboy 有印象么

**Comment by JervyShi** [comment]
@OrezzerO 举个例子：Resteasy 需要对所有的 Rest API 增加登录认证的 Filter，作用是拦截掉无登录信息的请求，如果这个 Filter 作用于 SOFA RPC，SOFA RPC 可用作进程间直接通讯，Rest 请求是默认可信的，Rest API 的调用可以没有登录信息，但是 Filter 共享后，请求将被拦截，无法正常响应。

**Comment by OrezzerO** [comment]
我的理解是这样子的:  所有只和 rest 相关的,用 Resteasy 的 filter ,那些能通用的,应该用 sofa 的 filter .如果通用的 filter 还用Resteasy 的 filter重写一遍就不是很优雅了. @JervyShi

**Comment by JervyShi** [comment]
@OrezzerO 理解你的意思了，SOFA RPC 的 Filter 是适用于所有协议的通用 Filter，只有单独为 Rest 定制的 Filter 走 `JAXRSProviderManager` 注入。

**Comment by OrezzerO** [comment]
@leizhiyuan 今天遇到一个问题和这个 issue 有关,想请教一下: 在javax.ws.rs.container.ContainerResponseFilter#filter 方法中,我怎么拿到这个请求对应的接口名和方法名?

**Comment by leizhiyuan** [comment]
嗯，这个在考虑合并中。 @OrezzerO O
