### ISSUE TITLE
Publishing multi rest service with same path by @SofaService should be warned or forbidden.

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-rpc#382]
### Describe the bug

@SofaService can be used  to publish rest service by marking binding type as `rest`, multi rest services with same url would be overridden, even they are configured with different unique-id.

Maybe we should print some warning log or prevent the application to launch.

### Environment

- SOFARPC version: 5.4.7
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
MultipleEndpointsWarningTest  resteasy seems only print a error log.
