### ISSUE TITLE
支持服务路由吗？

### ISSUE THREAD

**Issue by xilipilige** [alipay/sofa-rpc#396]
是否像Dubbo那样支持Router

**Comment by leizhiyuan** [comment]
com.alipay.sofa.rpc.client.Router 扩展这个接口就可以了

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/issues/363

**Comment by JervyShi** [comment]
@xilipilige  Issue 先关闭了，还有疑问的话可以再打开。
