### ISSUE TITLE
Possible double check of field

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-rpc#397]
### Your question

BeanIdMatchFilter#needToLoad()
AbstractHttp2ServerTransport#start()
Both of them use the double-check locking in a broken way , the url below shows why
[http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html](url)

Are there any reason to do the double-check locking in such a non thread safe way? 

### Your scenes

describe your use scenes (why need this feature)

### Your advice

Maybe we should add volatile to the check variable or just delete the check outside the synchronized(this is  slower than previous)

### Environment

- SOFARPC version: 5.5.0-SNAPSHOT
- branch : master
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
Thanks for you suggest.  I think that is code defects. 
Can you fix it ?

**Comment by hqq2023623** [comment]
@ujjboy  Sure, I will fix it soon
