### ISSUE TITLE
统一异常处理

### ISSUE THREAD

**Issue by ilker8** [alipay/sofa-rpc#398]
### Your question

有没有异常统一处理的功能

### Your scenes

@PreMatching
public class CustomException implements ExceptionMapper<SofaRpcException> {
    @Override
    public Response toResponse(SofaRpcException e) {
        return Response.status(500).entity(R.error(e.getMessage())).build();
    }
}

CustomException customException = new CustomException();
JAXRSProviderManager.registerCustomProviderInstance(customException);

toResponse方法不执行
### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:5.4.7
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10
- Maven version:
- IDE version:2018.2

**Comment by leizhiyuan** [comment]
JAXRSProviderManager.registerCustomProviderInstance(customException);

 要先注册，放在main的入口处

**Comment by ilker8** [comment]
>           JAXRSProviderManager.registerCustomProviderInstance(customException);
> 要先注册，放在main的入口处

是放在SofaBootRpcSamplesApplication类的main方法里的

**Comment by ilker8** [comment]
> ![image](https://user-images.githubusercontent.com/2684384/49631038-83687980-fa2b-11e8-840c-ddd92c76dd2b.png)
> 你代码写错了。验证ok
> 
> ![image](https://user-images.githubusercontent.com/2684384/49631061-93805900-fa2b-11e8-8940-108a83d61946.png)
> 
> ```
> @PreMatching
> public class CustomException implements ExceptionMapper<SofaRpcException> {
> 
>     @Override
>     public Response toResponse(SofaRpcException exception) {
>         return Response.status(500).entity(exception.getMessage()).build();
>     }
> }
> ```

我是在xml里发布服务，在sofaboot里注册异常类的

**Comment by leizhiyuan** [comment]
是说在sofaboot中这样写不会生效？

**Comment by ilker8** [comment]
> 是说在sofaboot中这样写不会生效？

是的

**Comment by leizhiyuan** [comment]
你是在一个工程里同时存在客户端和服务端？

**Comment by ilker8** [comment]
> 你是在一个工程里同时存在客户端和服务端？

工程里只有服务端，客户端用的是postman工具。Axios请求也是一样的

**Comment by leizhiyuan** [comment]
ok,了解了。我验证下。

**Comment by leizhiyuan** [comment]
我验证是可以的。你这边方便有一个demo么？

![image](https://user-images.githubusercontent.com/2684384/49708665-7934be00-fc6b-11e8-912e-ec79b55d2a1b.png)

![image](https://user-images.githubusercontent.com/2684384/49708673-7e920880-fc6b-11e8-825f-bbfdc1e059dc.png)

**Comment by ilker8** [comment]
> 我验证是可以的。你这边方便有一个demo么？
> 
> ```
> <parent>
> 		<groupId>com.alipay.sofa</groupId>
> 		<artifactId>sofaboot-dependencies</artifactId>
> 		<version>3.0.0</version>
> 	</parent>
> ```
> ![image](https://user-images.githubusercontent.com/2684384/49708665-7934be00-fc6b-11e8-912e-ec79b55d2a1b.png)
> 
> ![image](https://user-images.githubusercontent.com/2684384/49708673-7e920880-fc6b-11e8-825f-bbfdc1e059dc.png)

怎么给你？

**Comment by leizhiyuan** [comment]
push 到你的开源仓库，然后我拉下来看下？

**Comment by ilker8** [comment]
> push 到你的开源仓库，然后我拉下来看下？
我发给鲁直了
@PreMatching
public class CustomException implements ExceptionMapper<SofaRpcException> {

    @Override
    public Response toResponse(SofaRpcException exception) {
        return Response.status(500).entity(exception.getMessage()).build();
    }
}
只能处理SofaRpcException，Mybatis异常不能处理是吧

**Comment by leizhiyuan** [comment]
是的。你的代码里没有抛出SofaRpcException的异常，所以这里不会处理的。这是rest的匹配逻辑。你可以写一个ExceptionMapper，匹配更广泛的异常

**Comment by ilker8** [comment]
> 是的。你的代码里没有抛出SofaRpcException的异常，所以这里不会处理的。这是rest的匹配逻辑。你可以写一个ExceptionMapper，匹配更广泛的异常

好的，谢谢你

**Comment by leizhiyuan** [comment]
ok，如果有其他问题，可以再开issue
