### ISSUE TITLE
Remove jdk6 test case in travis ci.

### ISSUE THREAD

**Issue by JervyShi** [alipay/sofa-rpc#403]
### Describe the bug

```
Installing openjdk6
$ export JAVA_HOME=~/openjdk6
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/openjdk6" --workspace "/home/travis/.cache/install-jdk" --feature "6" --license "GPL"
install-jdk.sh 2018-10-17
Expected feature release number in range of 9 to 12, but got: 6
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk6" --workspace "/home/travis/.cache/install-jdk" --feature "6" --license "GPL"" failed and exited with 3 during .
Your build has been stopped.
```

Travis CI build failed when using open jdk6, Perhaps it's time to give up jdk6.

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
group: edge
 did you try this way?

**Comment by JervyShi** [comment]
@leizhiyuan Jest add `group: edge` ？I will give it a try.

**Comment by leizhiyuan** [comment]
yes https://github.com/B3Partners/brmo/commit/b6be26268f4a68ccc21820d4d71c42098724850f

if it is not ok, just give up jdk6

**Comment by JervyShi** [comment]
@leizhiyuan Just failed again. https://github.com/JervyShi/test-travis-ci/commit/127c83801bf49dae5b156f0f9f02a393031ec780

**Comment by leizhiyuan** [comment]
ok。just remove it
