### ISSUE TITLE
com.alipay.sofa.rpc.tracer.sofatracer.factory.MemoryReporterImpl#doReport

### ISSUE THREAD

**Issue by juaby** [alipay/sofa-rpc#407]
com.alipay.sofa.rpc.tracer.sofatracer.factory.MemoryReporterImpl#lock
at
com.alipay.sofa.rpc.tracer.sofatracer.factory.MemoryReporterImpl#doReport
除了IOException，就不可能有别的EX存在吗

**Comment by leizhiyuan** [comment]
这个类是给测试代码使用的，不在正是代码中使用，这里也可以捕获更广的异常。有兴趣可以提个pr
