### ISSUE TITLE
Can you support the component

### ISSUE THREAD

**Issue by limx198918** [alipay/sofa-rpc#41]
Micro service R & D framework, RPC framework, service registry, distributed timing task, flow limiting / fusing framework, dynamic configuration push, distributed link tracking, Metrics monitoring and measurement, distributed high availability message queue, distributed transaction framework, distributed database agent layer

**Comment by leizhiyuan** [comment]
something you said, like service registry should not be implemented by rpc, It should be a independent product like zk.  distributed high availability message queue too . 

please see  https://github.com/alipay/sofa-rpc/wiki/RoadMap to know what sofa-rpc will do next, including distributed link tracking ,or you can contribute.

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/wiki/RoadMap#%E7%89%88%E6%9C%AC%E8%BF%AD%E4%BB%A3%E8%AE%A1%E5%88%92

you can see the plan here. we will update the table soon.

**Comment by limx198918** [comment]
Can hystrix provide support? Or is it our own extra to add

**Comment by khotyn** [comment]
@limx198918 It is your own extra to add. But we have rate limit, melt down framework in Ant Financial, we'll open source it in the future.
