### ISSUE TITLE
Is it necessary to load local file when LocalRegistry#init

### ISSUE THREAD

**Issue by ScienJus** [alipay/sofa-rpc#419]
### Your question

#412 之后的疑问

`LocalRegistry#init` 中，最开始并没有从文件中读取 Provider 信息，但是依旧计算了 lastDigest，假设程序启动时本地已经有了一个文件（例如程序故障重启了），因为 lastDigest 会一直和 init 时的相同，那么在下次更新之前定时 task 是不是都不会读取这个文件？

### Your advice

在 init 时检查如果文件存在就 load 到内存缓存中，是否更符合实际的使用场景？

**Comment by leizhiyuan** [comment]
可以的。
