### ISSUE TITLE
应用启动之后立即退出,没有打印异常

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#424]
### Your question

 我们自己加了一个 jaeger 的 tracer 模块.  应用启动之后立马触发 shutdown hook 然后关闭了,我们打开了 debug 日志,日志里面看不到有错误抛出来.

没有 DEBUG 的头绪,大家有 DEBUG 的建议吗?

### Environment

- SOFARPC version:5.4.8
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
@OrezzerO 可否提供下问题的复现的步骤和方式呢？

**Comment by leizhiyuan** [comment]
如果没有任何非daemon的后台线程，是可能出现这样的，看下是不是没有发布过任何服务。bolt，rest等都没有。

**Comment by OrezzerO** [comment]
是有发布过服务的，并且用sofaTracer 时是好的

**Comment by leizhiyuan** [comment]
提供一个可复现的demo 到你的公开仓库？

**Comment by OrezzerO** [comment]
有点难，我们内部依赖比较多🙈，想了解下你们如果遇到这种问题，有哪些debug的思路

**Comment by khotyn** [comment]
Jaeger 我记得是基于字节码搞的？有没有可能字节码的修改导致 JVM Crash，可否看下有没有 Crash 日志？

**Comment by leizhiyuan** [comment]
···
-XX:HeapDumpPath=/home/admin/logs -XX:ErrorFile=/home/admin/logs/hs_err_pid%p.log
···

加下这两个参数，启动，看看crash的时候，是否会生成日志。在这个目录下。

**Comment by OrezzerO** [comment]
嗯好的，明天我试一下，现在手头没有工具

**Comment by OrezzerO** [comment]
加上参数之后没有日志打印出来,我在 main 函数里启动了一个每秒打印 "hello" 的线程之后,应用就不退出了, 测试发布的 rest 服务是可用的

**Comment by khotyn** [comment]
@leizhiyuan 是否可能跟 #370 有关。

**Comment by leizhiyuan** [comment]
没关系的，https://github.com/alipay/sofa-rpc/releases/tag/v5.4.8 548已经没有这个问题了。

**Comment by OrezzerO** [comment]
https://github.com/OrezzerO/sofa-demo-simple 已经上传了,我修改了rpc-config.json: `  "default.tracer" : ""
`

**Comment by leizhiyuan** [comment]
用sofaboot不要操作rpc-config.json文件,547版本即可，配置一下

```
com.alipay.sofa.rpc.rest-daemon=false
```
就行了

[rest.patch.zip](https://github.com/alipay/sofa-rpc/files/2674813/rest.patch.zip)

**Comment by OrezzerO** [comment]
@leizhiyuan 我们的问题是我们自己写了一个 tracer 模块,想要替换原来的 `sofaTracer` 模块,这就需要改动`rpc-config.json`了吧,改动过后就出现启动立即关闭的问题了.

**Comment by leizhiyuan** [comment]
怎么复现？我看现在```com.alipay.sofa.rpc.rest-daemon=false``` 之后是没问题的。 你们那个模块能否写个空实现这样？

**Comment by OrezzerO** [comment]
@leizhiyuan 我理解错了,我这边已经能成功启动了,十分感谢~ By the way ,这个算是 feature 还是 bug呢?

**Comment by leizhiyuan** [comment]
@OrezzerO 以前涉及的时候觉得这种合理，现在实际中觉得还是不应该做默认后台，这个已经在548中fix了。rpc starter这两天发一个版本来fix
