### ISSUE TITLE
SnappyDecompressor#decompressTagSlow()

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-rpc#435]
### Your question

switch没有default和break

```
 switch (trailerBytes) {
    case 4:
        trailer = (input[ipIndex + 3] & 0xff) << 24;
    case 3:
        trailer |= (input[ipIndex + 2] & 0xff) << 16;
    case 2:
        trailer |= (input[ipIndex + 1] & 0xff) << 8;
    case 1:
        trailer |= (input[ipIndex] & 0xff);
} 
```
### Your advice

可以加上default和break

### Environment

- SOFARPC version: 5.5.0-SNAPSHOT
- branch : master
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
ok~有兴趣可以帮忙提个pr。提到mater即可。之后如果有变更，这个地方可能会被遗漏。

**Comment by leizhiyuan** [comment]
It seems not to be a bug，it is a feature
