### ISSUE TITLE
why not implement com.alipay.sofa.rpc.protocol.Protocol in Bolt?

### ISSUE THREAD

**Issue by Authorlove** [alipay/sofa-rpc#44]
What's your suggestion for implementing my own protocol? Do I need to rely the protocol manager of Bolt?

**Comment by ujjboy** [comment]
[Bolt](https://github.com/alipay/sofa-bolt) is a special internal protocol. The serialization and codec parts have been implemented by itself. If the Bolt implement `com.alipay.sofa.rpc.protocol.Protocol`, some reconstruction work is needed.

**Comment by leizhiyuan** [comment]
closed, If you have any question  associated with this, please reopen it
