### ISSUE TITLE
接收数组类型的数据

### ISSUE THREAD

**Issue by ilker8** [alipay/sofa-rpc#442]
### Your question

前端list?ids[]=3&ids[]=4
后台服务:
@GET
@Path(value = "/list")
Response list(@QueryParam("ids") List<String> ids);
ids为空
### Your scenes

正常接收数据类型的数据

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:5.4.7
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):win10
- Maven version:3.0.3
- IDE version:2018.2

**Comment by leizhiyuan** [comment]
rest的标准是下面这样。

http://127.0.0.1:8888/rest/list?ids=1&ids=2 应该是这样，我这边测试过了。
