### ISSUE TITLE
有类似Spring Cloud Bus  功能组件吗

### ISSUE THREAD

**Issue by 18970952785** [alipay/sofa-rpc#450]
有类似Spring Cloud Bus  功能组件吗，，配置库配置信息有变化 ，如何通知各服务组件

**Comment by JervyShi** [comment]
@18970952785 你是指应用配置信息还是 SOFA RPC 的配置信息？应用配置可以对接 spring-cloud-config 或者 apollo, SOFA RPC 的服务治理是和注册中心对接实现相关的。

**Comment by JervyShi** [comment]
@18970952785  Issue 先关闭了，还有疑问的话可以再打开。
