### ISSUE TITLE
直连调用${appserverIp}不支持

### ISSUE THREAD

**Issue by opjkjava** [alipay/sofa-rpc#451]
### Describe the bug

期望服务端和客户 使用直接调用,不使用注册中心. 如下配置出错.
<sofa:reference jvm-first="false" id="sofaRpcService" interface="rpc.SofaRpcBaseService">
        <sofa:binding.bolt>
                  <sofa:route target-url="bolt://${appserverIp}:12200"/>
        </sofa:binding.bolt>
    </sofa:reference>
 appserverIp 是application.properties中定义的.
将变量替换成具体的ip地址,       <sofa:route target-url="bolt://192.168.8.13:12200"/>,调用成功. 

### Expected behavior
${appserverIp} 应该自动替换成application.properties中配置ip地址.  @Value("${appserverIp}") 注解也不支持.

### Actual behavior
SofaRouteException: RPC-02306: 没有获得服务[rpc.SofaRpcBaseService:1.0]的调用地址，请检查服务是否已经推送 

### Environment
compile group: 'com.alipay.sofa', name: 'rpc-sofa-boot-starter', version: '6.0.0'
compile group: 'com.alipay.sofa', name: 'runtime-sofa-boot-starter', version: '3.1.0'

- SOFARPC version: 
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/50407451-37cb1380-0812-11e9-88ea-51a55928731d.png)

![image](https://user-images.githubusercontent.com/2684384/50407453-40bbe500-0812-11e9-9a11-60ccd84dd04a.png)


xml中我这边测试是ok的。这个是spring原生支持的。能否提供一个可复现的demo？

https://github.com/alipay/sofa-boot/pull/264 注解的支持在2.5.2中合并了。马上发布的sofaboot 3.x 也会同步支持。

**Comment by opjkjava** [comment]
问题已经解决
