### ISSUE TITLE
如何获得在注册中心中已注册服务的provider信息

### ISSUE THREAD

**Issue by VincentSleepless** [alipay/sofa-rpc#453]
### Your question
某些case下需要一个IP4地址下，某个service只能注册一个provider，但是目前无法获得在注册中心中注册服务的provider信息。

### Your scenes
RpcRuntimeContext貌似无法获得多个进程间cache或者已经注册的provider信息。
![image](https://user-images.githubusercontent.com/15063109/50411467-277b5e80-083b-11e9-89fc-9780bb9e1b42.png)

测试结果如下：
step1: 注册服务并cache到RpcRuntimeContext当中
provider已经注册
![image](https://user-images.githubusercontent.com/15063109/50411335-2a298400-083a-11e9-90c1-d76029ac23ac.png)
zk已经注册
![image](https://user-images.githubusercontent.com/15063109/50411343-36addc80-083a-11e9-9054-c3194018d1a2.png)

step2:启动一个consumer前尝试获得 RpcRuntimeContext中的getProviderConfigs()信息
![image](https://user-images.githubusercontent.com/15063109/50411481-41b53c80-083b-11e9-8fdb-0fead56c2719.png)
返回的信息为空。。。

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
你是在分布式环境下，希望获取注册中心里面的服务提供方信息？直接操作zk 呢？

**Comment by leizhiyuan** [comment]
自定义路由和负载都不需要你操作zk，在你扩展Router的时候，里面的地址列表就是你需要的。

com.alipay.sofa.rpc.client.router.RegistryRouter 可以参考

**Comment by leizhiyuan** [comment]
没问题的话，先关闭了，有疑问可以再打开。
