### ISSUE TITLE
为什么客户端要取名为Cluster

### ISSUE THREAD

**Issue by reenWYJ** [alipay/sofa-rpc#460]
对这个命名不是太理解

**Comment by leizhiyuan** [comment]
支持服务端是集群的Client

**Comment by reenWYJ** [comment]
> 支持服务端是集群的Client

服务端是集群,和客户端无关吧?

@leizhiyuan

**Comment by JervyShi** [comment]
@reenWYJ SOFA RPC 提供服务一端可以称之为服务端，调用服务的一端可以称为客户端，但是他们用的都是 SOFA RPC 的能力，你描述的客户端指的是什么？SOFA RPC 包？

**Comment by JervyShi** [comment]
@reenWYJ 是的

**Comment by leizhiyuan** [comment]
先关闭了。有疑问可以在打开。
