### ISSUE TITLE
关于classloader的问题

### ISSUE THREAD

**Issue by wangyijunjunjun** [alipay/sofa-rpc#461]
![](https://ws1.sinaimg.cn/large/006tNbRwgy1fymjjvzcuej31c00u0ayn.jpg)

这里为什么要切换classloader呢?

**Comment by JervyShi** [comment]
SOFA RPC 支持在框架和应用使用独立 ClassLoader 的场景，在涉及到需要触发业务方法请求时切换 ClassLoader 可以避免出现由于 ClassLoader 不同导致的各类异常。

**Comment by JervyShi** [comment]
@wangyijunjunjun Issue 先关闭了，还有疑问的话可以再打开。
