### ISSUE TITLE
自定义路由筛选问题

### ISSUE THREAD

**Issue by VincentSleepless** [alipay/sofa-rpc#465]
### Your question

写了一个基于provider所在服务器资源的路由筛选器，在RPC请求时根据SofaRequest请求参数筛选可用的providerInfo，若筛选的信息为空，让然可以RPC路由到某一个provider服务提供方，是否有默认的路由地址？

### Your scenes

@Extension(value = "jobPushRegistry", order = -20000)
@AutoActive(consumerSide = true)
public class JobPushRegistryRouter extends Router {

    private final static Logger logger = LoggerFactory.getLogger(JobPushRegistryRouter.class);

    /* route path : job load registry  */
    private static final String RPC_JOB_PUSH_REGISTRY_ROUTER = "jobPushRegistry";
    /* consumer service bootstrap  */
    private ConsumerBootstrap consumerBootstrap;

    @Override
    public void init(ConsumerBootstrap consumerBootstrap) {
        this.consumerBootstrap = consumerBootstrap;
    }

    @Override
    public boolean needToLoad(ConsumerBootstrap consumerBootstrap) {
        ConsumerConfig consumerConfig = consumerBootstrap.getConsumerConfig();
        //if not direct connect then subscribe registry config
        return StringUtils.isEmpty(consumerConfig.getDirectUrl()) && consumerConfig.isSubscribe();
    }

    @Override
    public List <ProviderInfo> route(SofaRequest request, List <ProviderInfo> providerInfos) {
        ExePushJobRequest jobRequest = parseSofaRequest(request);
        JobInfo jobInfo = jobRequest.getJobInfo();
        List <ProviderInfo> availableProviders = parseAvailableProvider(jobInfo, providerInfos);
        recordRouterWay(RPC_JOB_PUSH_REGISTRY_ROUTER);
        return availableProviders;
    }

   private List <ProviderInfo> parseAvailableProvider(JobInfo jobInfo, List <ProviderInfo> providerInfos) {
         if（available）{
            //return 一个可用的route列表
         }else{
           //return null ; 
        }
   }
 }

根据作业资源分配查看，若parseAvailableProvider（jobInfo,providerInfo）方法返回为空，则代表没有provider所在的ecs有足够的资源可以执行某个作业；但这个时候会默认发送到任意（不是很清楚机制）的一台服务器上；

如果想实现rpc框架级别的阻止资源不足的请求可以被路由，被负载均衡？
单独使用自定义route是否没有作用，还要配合自定义的LoadBalancer进行处理？

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:  5.4.8
- JVM version (e.g. `java -version`): openjdk 10.0.2
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@VincentSleepless   路由的作用就是从一组地址里面筛选出有一组地址，负载均衡是从路由结果里选择一个地址（如果路由结果没地址则不走负载均衡）

你的需求是否是走你的自定义Router之后，如果地址，就走一个新的不在当前服务列表内的地址？

**Comment by VincentSleepless** [comment]
我的意思是，如果所有的provider资源都满了，我的自定义路由的返回的路由列表就是空，这样我在rpc service的时候应该抛出没有可用provider的异常，而测试的时候，竟然在return null的时候调痛了～

**Comment by VincentSleepless** [comment]
@leizhiyuan  我发现，在加载自定义Router的时候会有重复加载，且会默认加载内置的相关Routers
![image](https://user-images.githubusercontent.com/15063109/50579681-43f24900-0e82-11e9-8fcc-4a62f92727b1.png)

从而导致Router.route返回为空的情况下,AbstractCluster.select方法中，没有抛出预想的异常。
![image](https://user-images.githubusercontent.com/15063109/50579707-7439e780-0e82-11e9-80e5-ae65a1bf8a27.png)

**Comment by leizhiyuan** [comment]
有复现的示例可以提交下么？我来看看。

**Comment by VincentSleepless** [comment]
@leizhiyuan 默认继承Router会出现上述问题，我再尝试另外一个ExcludeRouter(default)或者ExcludeRouter(*)
