### ISSUE TITLE
rest filter初始化失败导致rest接口404

### ISSUE THREAD

**Issue by rayzeng** [alipay/sofa-rpc#467]
### Describe the bug

rest filter构造方法抛出RuntimeExcption，此时异常在RestServer中被catch住，正常启动，但此时调用rest接口会返回404

`
@Provider
@Priority(210)
public class MyFilter implements ContainerRequestFilter {
    @Autowired
    TestService testService;

    public MyFilter(){
        throw new RuntimeException("test");
    }
    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
        System.out.println("============== MyFilter filter ==============");
    }
`

`JAXRSProviderManager.registerInternalProviderClass(MyFilter.class);`

建议如果有RuntimeExcption不要catch，需要抛出让进程启动失败

### Environment

- SOFARPC version: 5.4.7
- JVM version (e.g. `java -version`):1.8

**Comment by rayzeng** [comment]
registerProcessor 捕获到的异常，健康检测是通过的

**Comment by leizhiyuan** [comment]
这里之前捕获异常是因为为了避免一个服务影响所有的服务发布。

![image](https://user-images.githubusercontent.com/2684384/51068611-7c044380-165b-11e9-8524-5398ee0852e2.png)


现在看，对于rest这种存在全局Filter异常的可能不太合适。另外，健康检查没有判断出来也是因为这里捕获了异常。

![image](https://user-images.githubusercontent.com/2684384/51068606-5bd48480-165b-11e9-98bb-32bc9c683a0e.png)

会尽快修复。
