### ISSUE TITLE
com.alipay.sofa.rpc.listener.ConfigListener#configChanged 没有具体实现?

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#470]
### Your question

ConsumerAttributeListener 和 ProviderAttributeListener 都没有实现 configChanged . 想了解下原因和后续计划.

### Environment

- SOFARPC version: 5.4.8
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by ujjboy** [comment]
@OrezzerO 这个方法本来是给注册中心推送一些动态的服务配置用的。 后续我们会重构下，将动态配置模块从注册中心里剥离出来成为一个独立的扩展点。
