### ISSUE TITLE
前后端不分离的应用的实践

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#477]
### Your question

对于一些应用,由于一些原因,不想前后端分离.有好的实践吗? 
是暴露两个接口,spring mvc 和 easyrest 分别提供前端支持和 rest 接口支持 ,还是上在 resteasy 上做一些工作来支持?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
你可以在mvc的那个controller里调用rest的接口（这时候作为的是普通方法）。
不过最好还是分离吧。前后端用json来数据交互。以后更好维护和升级。

**Comment by OrezzerO** [comment]
恩,已经推荐小伙伴把服务层次分开来
