### ISSUE TITLE
HystrixFilter blocks an async request

### ISSUE THREAD

**Issue by ScienJus** [alipay/sofa-rpc#478]
### 描述

这是一个 bug，当使用异步请求 `INVOKER_TYPE_FUTURE` 并开启 `Hystrix` 时，`HystrixFilter` 会将异步请求变为同步请求。

https://github.com/alipay/sofa-rpc/blob/8f07447dd85f83818db8bf9fe50716de86960e04/extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixObservableCommand.java#L109

因为这一行中 `this.toObservable()` 会阻塞当前线程直到请求完成。

### 原因

主要原因在于 Hystrix 只能定义一段完整的逻辑，没办法将一段逻辑是否执行（包含熔断、线程池拒绝逻辑）和是否异步执行分开。

在异步模式下 `invoker.invoke(request)` 必须要同步执行（这样才能在其执行后拿到 Future 并进行代理），同时我们又希望其在熔断、线程池拒绝等场景不进行执行，所以将其定义在 `HystrixCommand#run` 和 `HystrixObservableCommand#construct` 中，所以导致整个请求逻辑都变成了同步执行。

### 解决方案

一个可选的额解决方案是将异步模式下的 `invoker.invoke(request)` 执行移出 `run/construct`， 直接在 `invoke` 中同步执行，然后通过`HystrixCommand#queue` 包装 `Future`，例如：

```
@Override
public SofaResponse invoke() {
    if (isCircuitBreakerOpen() && LOGGER.isWarnEnabled(invoker.getConfig().getAppName())) {
        LOGGER.warnWithApp(invoker.getConfig().getAppName(), "Circuit Breaker is opened, method: {}#{}",
            invoker.getConfig().getInterfaceId(), request.getMethodName());
    }
    this.sofaResponse = invoker.invoke(request);
    this.responseFuture = RpcInternalContext.getContext().getFuture();
    RpcInternalContext.getContext().setFuture(new HystrixResponseFuture(this.queue(), this.responseFuture));
    return sofaResponse;
}

@Override
protected Object run() throws Exception {
    return this.responseFuture.get();
}
```

这样能保证异步逻辑没有被破坏，问题是当出现熔断或是线程池拒绝时，虽然 Hystrix 不会实际执行 run 方法，但是请求依旧会发出。此时我们不希望真正发出请求，但是 Hystrix 并没有提供标准方法在执行前人工判断是否可以执行请求。

再想想有没有其他方案…

**Comment by CodingSinger** [comment]
在construct中` return Observable.from(this.responseFuture, Schedulers.newThread());`能解决这个问题？

**Comment by CodingSinger** [comment]
没办法把run中get的和`invoke`返回的future再做个关联吗
