### ISSUE TITLE
About the value of RpcConstants.REGISTRY_PROTOCOL_ZK

### ISSUE THREAD

**Issue by rwsbillyang** [alipay/sofa-rpc#481]
```
RegistryConfig registryConfig = new RegistryConfig()
			.setProtocol(RpcConstants.REGISTRY_PROTOCOL_ZK)//.setProtocol("zookeeper")   is ok
			.setAddress("127.0.0.1:2181");
```
The app reports ill protocol if uses `setProtocol(RpcConstants.REGISTRY_PROTOCOL_ZK)`, REGISTRY_PROTOCOL_ZK cannot be used here, or its value ("zooKeeper") is not right?

**Comment by leizhiyuan** [comment]
could you please provide a demo for this issue？

**Comment by khotyn** [comment]
@leizhiyuan It seems that `REGISTRY_PROTOCOL_ZK` is never used.

**Comment by leizhiyuan** [comment]
yes,the code in Starter  did the thing, 

@rwsbillyang please use zookeeper ,you can see com.alipay.sofa.rpc.registry.zk.ZookeeperServerRestartTest

**Comment by leizhiyuan** [comment]
ok， we will summary some constants into SOFARPC project soon。
