### ISSUE TITLE
Cannot provent sofaTracer from logging on disk, by set "sofa.middleware.log.disable=true"

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#491]
### Describe the bug

Cannot provent sofaTracer from logging on disk, by set "sofa.middleware.log.disable=true"

### Environment

- SOFARPC version: 5.4.8
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
这个不能关闭tracer，只是关闭统一的日志输出。要关闭tracer功能，可以在启动时中传入

`-Ddefault.tracer=`

**Comment by khotyn** [comment]
@leizhiyuan 关闭 Tracer 的功能应该在 alipay/sofa-rpc-boot-projects#150 这个 PR 中提供

**Comment by OrezzerO** [comment]
@leizhiyuan 并不是想关闭 Tracer ,而是说无法阻止 Tracer 打印本地日志. `sofa.middleware.log.disable=true`这个配置对于 Tracer 日志不生效,是不是不太好?

**Comment by OrezzerO** [comment]
在我们主流的应用场景下,我们已经自己实现了一个 tracer 进行调用链监控.在少数场景下面,用的是原生 sofa-rpc. 已经在环境变量中设置'sofa.middleware.log.disable=true',我们自己实现的那个 tracer ,已经没有本地日志了.但在原生sofa-rpc 的情况下, 还是会打印 sofa-tracer 的本地日志.

我原先是以为sofa-tracer 除了打印本地日志还会做上报的工作,又回头看了下文档,应该是没有.

我现在的做法是在`rpc-config.json`里面禁用了 sofa-tracer.  我这边已经没有问题了, 

我提这个 issue 的原因是想讨论下,sofa tracer 自己写文件这个行为是不是合适. 现在很多应用跑在容器里面,写本地文件容易丢失,而且在没有合适工具的前提下, 不同应用的这些本地文件很难串联起来,所以我觉得这里 sofa tracer 自己写本地文件是件挺奇怪的事情.

**Comment by leizhiyuan** [comment]
这个以前这样实现，是因为考虑到这时一个非常基础的功能，如果连这个都依赖业务的日志配置，那时候，还没有sofa-middleware-log这个东西。所以都是sofatracer自己实现了。

考虑到你说的情况，一种替代的方案是容器中的日志采集，这个用容器中的agent也是可以的，另一种，这个可能需要sofatracer的同学看下是否可以支持写远程文件，或者上传这种方式了。

@glmapper

**Comment by OrezzerO** [comment]
@leizhiyuan 这个 Issue 我这边没有问题了, 如果你觉得需要关掉,可以关掉这个 Issue .
