### ISSUE TITLE
我看编译出好多jar，测试允许哪些（个）jar?

### ISSUE THREAD

**Issue by longsebo** [alipay/sofa-rpc#495]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by longsebo** [comment]
主干版本

**Comment by leizhiyuan** [comment]
什么意思？

**Comment by longsebo** [comment]
不好意思，运行写出允许

**Comment by longsebo** [comment]
试了，报如下错误：
F:\git\sofa\sofa-rpc\all\target>java -jar sofa-rpc-all-5.5.0.jar
sofa-rpc-all-5.5.0.jar中没有主清单属性

**Comment by leizhiyuan** [comment]
你运行这个做什么呢？这是个jar包，没有main方法的。不能直接运行

**Comment by longsebo** [comment]
我目的就是要验证一下，能否告诉我运行哪个jar或者war?

**Comment by khotyn** [comment]
@longsebo 你是要跑 SOFARPC 的 Demo 吗？

**Comment by longsebo** [comment]
是的

**Comment by leizhiyuan** [comment]
要跑example在这里。先启动server，在启动client
![image](https://user-images.githubusercontent.com/2684384/51820964-6147f500-2312-11e9-9f5f-f1e979ee2ab8.png)

**Comment by longsebo** [comment]
好的，多谢，我试试，这个沟通挺那个的，能否用im工具沟通

**Comment by leizhiyuan** [comment]
项目代码相关的issue相对要更高效一点，其他的交流可以加这个群

![image](https://user-images.githubusercontent.com/2684384/51821187-3dd17a00-2313-11e9-8f7a-6f2d33f083b9.png)
。

**Comment by longsebo** [comment]
试了，报错如下：
Tests in error:
  testProviderObserver(com.alipay.sofa.rpc.registry.nacos.NacosRegistryTest): Failed to register provider to nacosRegistry!

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0

16:41:42.763 [SOFA-RPC-ShutdownHook] WARN com.alipay.sofa.rpc.context.RpcRuntimeContext - SOFA RPC Framework catch JVM shutdown event, Run shutdown hook now.
16:41:42.763 [SOFA-RPC-ShutdownHook] INFO com.alipay.sofa.rpc.transport.ClientTransportFactory - Shutdown all client transport now!
16:41:42.763 [SOFA-RPC-ShutdownHook] WARN com.alipay.sofa.rpc.context.RpcRuntimeContext - SOFA RPC Framework has been release all resources ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] [SOFA] - RPC Framework ............................. SUCCESS [  2.985 s]
[INFO] sofa-rpc-core ...................................... SUCCESS [  0.408 s]
[INFO] sofa-rpc-exception ................................. SUCCESS [  2.556 s]
[INFO] sofa-rpc-common .................................... SUCCESS [  3.213 s]
[INFO] sofa-rpc-api ....................................... SUCCESS [  6.006 s]
[INFO] sofa-rpc-core-impl ................................. SUCCESS [  0.170 s]
[INFO] sofa-rpc-log ....................................... SUCCESS [  1.313 s]
[INFO] sofa-rpc-client .................................... SUCCESS [  7.643 s]
[INFO] sofa-rpc-codec ..................................... SUCCESS [  1.442 s]
[INFO] sofa-rpc-filter .................................... SUCCESS [  1.199 s]
[INFO] sofa-rpc-proxy ..................................... SUCCESS [  1.765 s]
[INFO] sofa-rpc-transport ................................. SUCCESS [  0.780 s]
[INFO] sofa-rpc-extension-impl ............................ SUCCESS [  0.670 s]
[INFO] sofa-rpc-extension-common .......................... SUCCESS [  5.250 s]
[INFO] sofa-rpc-api-compatible ............................ SUCCESS [  1.067 s]
[INFO] sofa-rpc-bootstrap-bolt ............................ SUCCESS [  0.880 s]
[INFO] sofa-rpc-test ...................................... SUCCESS [  0.149 s]
[INFO] sofa-rpc-test-common ............................... SUCCESS [  0.820 s]
[INFO] sofa-rpc-bootstrap-dubbo ........................... SUCCESS [  3.689 s]
[INFO] sofa-rpc-bootstrap-http ............................ SUCCESS [  0.865 s]
[INFO] sofa-rpc-bootstrap-rest ............................ SUCCESS [  0.860 s]
[INFO] sofa-rpc-codec-sofa-hessian ........................ SUCCESS [  2.307 s]
[INFO] sofa-rpc-codec-protobuf ............................ SUCCESS [  2.083 s]
[INFO] sofa-rpc-codec-jackson ............................. SUCCESS [  2.212 s]
[INFO] sofa-rpc-log-common-tools .......................... SUCCESS [  1.276 s]
[INFO] sofa-rpc-remoting-bolt ............................. SUCCESS [  9.595 s]
[INFO] sofa-rpc-fault-tolerance ........................... SUCCESS [ 51.958 s]
[INFO] sofa-rpc-fault-hystrix ............................. SUCCESS [  1.117 s]
[INFO] sofa-rpc-registry-consul ........................... SUCCESS [08:48 min]
[INFO] sofa-rpc-registry-local ............................ SUCCESS [  1.946 s]
[INFO] sofa-rpc-registry-zk ............................... SUCCESS [  9.481 s]
[INFO] sofa-rpc-registry-nacos ............................ FAILURE [ 14.418 s]

**Comment by leizhiyuan** [comment]
你看下报错信息是什么，这是nacos的测试用例，windows上测试用例有些可能是不过的。主要是路径相关。

**Comment by longsebo** [comment]
我看了，没看到路径。难道window不支持nacos

**Comment by JervyShi** [comment]
@longsebo nacos 目前没有类似 consul 的内置 jar 来启动 nacos server，所以对 windows 的支持暂时还没有做，参见 #402 。

**Comment by longsebo** [comment]
欧克，终于过
