### ISSUE TITLE
bolt为什么不支持自己扩展序列化方式？

### ISSUE THREAD

**Issue by minli04g** [alipay/sofa-rpc#504]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
如果你说的是rpc的。com.alipay.sofa.rpc.codec.AbstractSerializer 实现这个抽象类就可以。

如果是直接使用了bolt，可以提给bolt的同学。

**Comment by minli04g** [comment]
BoltClientProxyInvoker.java
中，parseSerializeType对于其他类型序列化直接抛出异常了， 应该调用super.parseSerializeType


    @Override
    protected Byte parseSerializeType(String serialization) {
        Byte serializeType;
        if (SERIALIZE_HESSIAN.equals(serialization)
            || SERIALIZE_HESSIAN2.equals(serialization)) {
            serializeType = RemotingConstants.SERIALIZE_CODE_HESSIAN;
        } else if (SERIALIZE_PROTOBUF.equals(serialization)) {
            serializeType = RemotingConstants.SERIALIZE_CODE_PROTOBUF;
        } else if (SERIALIZE_JAVA.equals(serialization)) {
            serializeType = RemotingConstants.SERIALIZE_CODE_JAVA;
        } else {
            serializeType = super.parseSerializeType(serialization);
        }
        return serializeType;
    }

**Comment by khotyn** [comment]
@dbl-x 帮忙看一下哦～

**Comment by leizhiyuan** [comment]
这个在群里沟通过了。@minli04g 辛苦提个mr来改一下。
