### ISSUE TITLE
how about removing the formatting plugins from pom

### ISSUE THREAD

**Issue by minli04g** [alipay/sofa-rpc#512]
### Your question

it makes no sense to format the code before compiling. 
i have to revert those changes after compiling from the command line every time.

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
The purpose of the formatting plugin is to make sure everyone's code format keeps in consistent, so that there is no unnecessary code change when you submit a pull request.

**Comment by leizhiyuan** [comment]
if there was no other questions about this issue , I will close it, you can reopen it later.
