### ISSUE TITLE
SofaTracerPercentageBasedSampler 的sample方法优化

### ISSUE THREAD

**Issue by fredalxin** [alipay/sofa-rpc#514]
SofaTracerPercentageBasedSampler的sample方法没必要使用乐观锁吧，计数不用非要1-100重复，用long取余就好了貌似。

**Comment by khotyn** [comment]
@glmapper 看下哦~

**Comment by glmapper** [comment]
@fredalxin Thank you very much, I did a test, using the remainder method can save a lot of time in the case of high request volume, this will be handled in the performance optimization part(this is our [roadmap](https://www.sofastack.tech/sofa-tracer/docs/roadmap)), and you are welcome to give us PR

**Comment by leizhiyuan** [comment]
tracer 已经在tracer项目中优化。
