### ISSUE TITLE
How about use resteasy-jackson2-provider instead of resteasy-jackson-provider

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#517]
### Your question

Now, sofa rpc uses resteasy-jackson-provider. It uses `org.codehaus.jackson`,which is the old version of `com.fasterxml.jackson`. 

How about use resteasy-jackson2-provider instead of resteasy-jackson-provider,which is use `com.fasterxml.jackson`? 

### Environment

- SOFARPC version: 5.5.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
Do you need which version of com.fasterxml.jackson？

we need to test it。if we can upgrade to this version ，I will pr it。

**Comment by leizhiyuan** [comment]
we will update some deps in rpc 6.x ，if you do not need immediately，please wait some time

**Comment by OrezzerO** [comment]
get it

**Comment by leizhiyuan** [comment]
will be fixed in  https://github.com/alipay/sofa-rpc/pull/538
