### ISSUE TITLE
SofaRpcException  和 SofaRpcRuntimeException  的关系?

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#526]
### Your question

SofaRpcException  和 SofaRpcRuntimeException  的关系/区别是什么? 
他们都继承自 RuntimeException. 这么做的好处是什么?

求指教.

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by OrezzerO** [comment]
明确一下问题: SofaRpcException 为什么继承自 RuntimeException ,而不是 Exception?

**Comment by leizhiyuan** [comment]
@ujjboy  淮总看下呢。是不是当时有什么其他的考虑，设计上当时应该是
SofaRpcException 继承Exception 
SofaRpcRuntimeException 继承RuntimeException ？

**Comment by ujjboy** [comment]
SofaRpcRuntimeException 在框架运行加载阶段的都抛出这个异常，例如一些参数配置错误。
SofaRpcException 如果是 RPC 每次请求阶段出现的异常抛出这个异常，例如服务端出现序列化异常，客户端找不到地址等。  

继承自 RuntimeException 主要是为了无需在每一层的方法上都加上 throws 声明。

**Comment by OrezzerO** [comment]
了解了
