### ISSUE TITLE
SofaRPC泛化调用支持sofa应用中心的注册中心吗

### ISSUE THREAD

**Issue by UCSBGauchos** [alipay/sofa-rpc#536]
### Your question

我是金融云用户，最近在泛化调用时候碰到一个问题。网上的例子只有直连的例子。
ConsumerConfig<GenericService> consumerConfig = new ConsumerConfig<GenericService>()
                .setInterfaceId(packageName)
                .setGeneric(true)
                .setDirectUrl(rpcServer) （直连）
                .setTimeout(3000);

我想问这里如果不是直连，而是使用sofa应用中心的注册中心，怎么配置？
是否也是使用RegistryConfig? 能给个例子么

**Comment by leizhiyuan** [comment]
金融云的用户，请直接在金融云的后台提工单给售后团队。谢谢～

**Comment by UCSBGauchos** [comment]
嗯，比较急，所以先在这里问一下。
