### ISSUE TITLE
sofa-rpc发布服务到nacos配置中心,该进行哪些配置

### ISSUE THREAD

**Issue by chengcheng768** [alipay/sofa-rpc#539]
sofa-rpc发布服务到nacos配置中心,该进行哪些配置？

application.properties进行了下面的配置
com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848
spring.application.name=AppName

服务发布的时候,配置如下:
<bean id="helloService" class="com.mallcai.HelloServiceImpl"/>
    <sofa:service ref="helloService" interface="com.mallcai.HelloService">
        <sofa:binding.bolt/>
 </sofa:service>
sofa:binding 支持的值:bolt,dubbo,h2c,jvm,rest. ????????????,要想把服务发布到nacos配置中心,怎么进行配置呢???????

- SOFARPC version:
 > 
  ` <parent>
   <groupId>com.alipay.sofa</groupId>
		<artifactId>sofaboot-dependencies</artifactId>
		<version>3.0.0</version>
   </parent>`
- JVM version (1.8):
- OS version (e.g. `uname -a`):
- Maven version: 3.5
- IDE version:

**Comment by leizhiyuan** [comment]
sofa:binding 支持的值:bolt

推荐配置为bolt

其他的不需要了。

另外3.0.0 不支持，需要升级到 3.1.3 版本

**Comment by chengcheng768** [comment]
1亲,你是说3.0.0不支持将服务注册到nacos,要升级到3.1.3是吗.???
2 就算是将服务注册到nacos，sofa:binding 的值:还是 bolt ???

**Comment by khotyn** [comment]
@chengcheng768 对，bolt 表示的是通信协议，和服务注册中心选择什么没有关系。

**Comment by chengcheng768** [comment]
@khotyn @leizhiyuan 谢谢你们，向大神致敬

**Comment by leizhiyuan** [comment]
没问题的话，issue 先关了。其它问题可以新开issue
