### ISSUE TITLE
SOFA-RPC支持Consul服务注册

### ISSUE THREAD

**Issue by Moriadry** [alipay/sofa-rpc#54]
任务领取: 支持将服务注册到Consul并定时心跳检查、监听。麻烦帮忙添加到 https://github.com/alipay/sofa-rpc/wiki/RoadMap  :) @ujjboy

**Comment by ujjboy** [comment]
Hi @Moriadry  可与参考如下文档：

参与贡献：https://github.com/alipay/sofa-rpc/wiki/Contributing
扩展demo：https://github.com/ujjboy/sofa-rpc-extension-demo
也可以参考 registry-zookeeper 模块的实现。

**Comment by leizhiyuan** [comment]
hi,这块目前怎么样了? 有遇到什么问题么 @Moriadry

**Comment by ScienJus** [comment]
Consul 是少数支持反向请求 Server 进行健康检查的注册中心（支持 TCP/HTTP/gRPC），在实现 Consul 的 Register 时是否需要考虑到 Server 不同的 protocol 实现并使用不同的健康检查方式呢？还是一律使用 TCP 健康检查或是 TTL 的方式？
