### ISSUE TITLE
是否能提供下rest 协议的zipkin支持？

### ISSUE THREAD

**Issue by xiaohanfeidao** [alipay/sofa-rpc#543]
是否能提供下rest 协议的zipkin支持？

**Comment by leizhiyuan** [comment]
@lifesinger  tracer层面已经支持了我记得，有文档么。

**Comment by glmapper** [comment]
> @glmapper tracer层面已经支持了我记得，有文档么。

issue & pr : https://github.com/alipay/sofa-tracer/pull/131 
document : https://www.sofastack.tech/sofa-tracer/docs/ReportToZipkin

**Comment by leizhiyuan** [comment]
感谢 @glmapper  

请 @xiaohanfeidao  根据文档使用，如果有问题可以在tracer的issue中进行沟通。谢谢～

**Comment by xiaohanfeidao** [comment]
感谢 你们！

**Comment by xiaohanfeidao** [comment]
我直接通过sofarpc的 rest（不是spring mvc）调用另外一个应用的sofarpc的rest zipkin没有调用轨迹啊？是什么版本开始支持rest协议的，bolt支持，rest也支持吗？

**Comment by glmapper** [comment]
> 我直接通过sofarpc的 rest（不是spring mvc）调用另外一个应用的sofarpc的rest zipkin没有调用轨迹啊？是什么版本开始支持rest协议的，bolt支持，rest也支持吗？

SOFATracer 将 span 数据上报至 zipkin 目前就是通过 rest 协议上报的，从 2.3.0 版本开始支持。对于SOFARpc 来说，不管你使用的是 bolt 协议还是 rest 协议，对于TRACER上报数据是没有影响的。

PS:
1、先看下你是否有部署 zipkin 的服务端 
2、参考 https://www.sofastack.tech/sofa-tracer/docs/ReportToZipkin 看下是否正确使用了 zipkin 上报

**Comment by xiaohanfeidao** [comment]
不是通过rest协议上报Zipkin，是需要支持sofa rest的链路追踪，bolt协议是可以显示的，
demo地址：https://github.com/xiaohanfeidao/cloudware-sofa
我用的是nacos 0.6.0版本 
初衷是全部使用resteasy + netty这种方式的微服务架构，入口从 sofa rest调用开始，
现在测试的结果是不支持的，不知道是我代码有问题 还是本身就是不支持？
