### ISSUE TITLE
sofa rest 是否支持上报zipkin 参照issues 543

### ISSUE THREAD

**Issue by xiaohanfeidao** [alipay/sofa-rpc#545]
是否支持sofa rest的链路追踪，bolt协议是可以显示的，
demo地址：https://github.com/xiaohanfeidao/cloudware-sofa
我用的是nacos 0.6.0版本
http://localhost:9100/webapi/rest/doSofa/1111/2222/33333
初衷是全部使用resteasy + netty这种方式的微服务架构，入口从 sofa rest调用开始，
现在测试的结果是zipkin中没有调用信息，代码是否有问题还是本身就是不支持？

**Comment by ujjboy** [comment]
SOFARPC 版本是？

**Comment by xiaohanfeidao** [comment]
sofa-rpc-all的版本是5.5.0

**Comment by xiaohanfeidao** [comment]
查出来了 原因我的zipkin太低，低版本走的v1，现在的版本是v2,感谢章耿，确实是支持的！希望sofa rpc越来越好！

**Comment by xiaohanfeidao** [comment]
问题查出来是我自己的问题，原因是使用了低版本的zipkin 走的是V1，现在的版本是V2，sofa rpc 5.5.0是支持的，感谢章耿，sofa rpc是最棒的。
