### ISSUE TITLE
无法匹配配置文件里面的sofa

### ISSUE THREAD

**Issue by chengcheng768** [alipay/sofa-rpc#546]
### lineNumber: 11; columnNumber: 83; cvc-complex-type.2.4.c: 通配符的匹配很全面, 但无法找到元素 'sofa:service' 的声明。

`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:sofa="http://sofastack.io/schema/sofaboot"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
            http://sofastack.io/schema/sofaboot   http://sofastack.io/schema/sofaboot.xsd"
       default-autowire="byName">
    <bean id="demoService" class="com.cc.cloud.service.impl.DemoServiceImpl"/>
    <sofa:service ref="demoService" interface="com.cc.cloud.service.IDemoService">
        <sofa:binding.bolt/>
    </sofa:service>
</beans>`

` <groupId>com.alipay.sofa</groupId>
    <artifactId>sofaboot-dependencies</artifactId>
    <version>3.1.3</version>
    <packaging>pom</packaging>
`

### Environment

- SOFARPC version:
- JVM version (e.g. `1.8`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
能否提供一个复现的demo？

**Comment by leizhiyuan** [comment]
那先关闭了。如果还有问题，可以发一下demo看看。
