### ISSUE TITLE
配置了logging.path，但是sofatracer的日志文件仍记录在用户主文件夹中

### ISSUE THREAD

**Issue by ItxiaoDz** [alipay/sofa-rpc#556]
### Describe the bug
在springboot中（非Sofaboot）使用sofa-rpc，配置了logging.path属性，但是sofatracer的日志还是记录在了用户主文件夹中（${user.home}/logs/tracelog）。

> 不单单sofatracer的日志，其他sofa相关的日志，都记录在了用户主目录

logging.path试过配置在application.properties文件中和其他的配置文件中的情况，都不行。
我项目中的其他日志都是能正常输出到logging.path属性指定的目中的。

### Expected behavior
sofa相关日志能记录在logging.path属性指定的目中。
### Actual behavior
日志记录在用户主目录中。

### Environment

- SOFARPC version: 5.5.0 and 5.5.1
- JVM version (e.g. `java -version`): 1.8.0_60-b27
- OS version (e.g. `uname -a`): macOS 10.14.12 Darwin Kernel Version 18.2.0
- Maven version: Apache Maven 3.3.9
- IDE version: IDEA 2018.3.5

_另外，sofaboot环境下，使用rpc-sofa-boot-starter来使用sofarpc，日志能正常记录在指定文件夹中。_

**Comment by leizhiyuan** [comment]
tracer 不是通过log组件打印的，是tracer自己实现的操作文件，所以你配置这个是不会生效的， @glmapper  看下是否有办法让用户配置。

**Comment by straybirdzls** [comment]
@ItxiaoDz 工程中加一下 log-sofa-boot-starter 试试看

```xml
 <dependency>
    <groupId>com.alipay.sofa.common</groupId>
    <artifactId>log-sofa-boot-starter</artifactId>
    <version>1.0.18</version>
</dependency>
```

**Comment by ItxiaoDz** [comment]
> @ItxiaoDz 工程中加一下 log-sofa-boot-starter 试试看
> 
> ```
>  <dependency>
>     <groupId>com.alipay.sofa.common</groupId>
>     <artifactId>log-sofa-boot-starter</artifactId>
>     <version>1.0.18</version>
> </dependency>
> ```

@straybirdzls 这样可以解决。

不过在引入log-sofa-boot-starter时，它依赖的sofa-common-tools:1.0.18和sofa-rpc依赖的sofa-common-tools:1.0.12冲突了，要将sofa-rpc中的排除才行，不然启动项目会报错。

**Comment by ujjboy** [comment]
@ItxiaoDz 嗯，我们后面升级下 sofa-rpc 里的 sofa-common-tools 版本。

cc: @leizhiyuan

**Comment by leizhiyuan** [comment]
ok see https://github.com/alipay/sofa-rpc/issues/558
