### ISSUE TITLE
配置属性优先级的问题:

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#594]
### Your question

在官网上,有这么一段说明: 
>SOFARPC 里面的某些配置在服务提供方可以设置，在服务调用方也可以设置，比如调用的超时的 timeout 属性，这些配置的优先级为：
>
>线程调用级别设置 >> 服务调用方方法级别设置 >> 服务调用方 Reference 级别设置 >> 服务提供方方法级别设置 >> 服务提供方 Service 级别设置

就 Timeout 这个属性来说 ,比较 **服务调用方 Reference 级别设置** 和  **服务提供方 Service 级别设置**, 不应该是 timeout 短的优先级高吗?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
不是说，这个是控制权的问题。应该是以客户端配置的为准。因为可能这个客户端觉得5s能接受，另一个客户端觉得10s能接受，服务端的是一个推荐值。可以认为。

**Comment by OrezzerO** [comment]
假设 `客户端配置10秒 ,服务端配置5秒`, 最终的超时时间是10秒?

**Comment by leizhiyuan** [comment]
是的。

**Comment by OrezzerO** [comment]
了解了,十分感谢!
