### ISSUE TITLE
@SofaReference是否可以在sofaboot中不通过注解方法获取

### ISSUE THREAD

**Issue by cxc3214** [alipay/sofa-rpc#597]
### 有一个静态类需要使用sofa的service

当前使用的是sofa-boot包，有些service可以通过@SofaReference获取，但是静态类中如果要使用sofa的service
是不是只能通过 “编程 API 方式”
有没有其他办法？

### Environment

- SOFARPC version: 2.6.2
- JVM version 1.8
- OS version :win10
- Maven version: 3.5.4
- IDE version: eclipse

**Comment by leizhiyuan** [comment]
@QilongZhang  这个帮忙看下。

**Comment by QilongZhang** [comment]
看你静态类怎么使用，如果你发布成 Bean，也是可以使用注解拿服务的。另外 API 需要通过 ClientFactoryAware 接口或者 @ SofaClientFactory 注解拿到，也是要在 Spring 上下文生命周期中操作。

**Comment by cxc3214** [comment]
@ SofaClientFactory  需要spring @ Commpent上下文才能用？ 能不能通过 SofaRuntimeContext 中获取到？
SofaRuntimeContext 静态类可以获取到吗？

**Comment by QilongZhang** [comment]
> @ SofaClientFactory 需要spring @ Commpent上下文才能用？ 能不能通过 SofaRuntimeContext 中获取到？
> SofaRuntimeContext 静态类可以获取到吗？

以上两种是官方推荐的两种方式，你可以自己封装一下的。如果完全不想和 Spring  上下文打交道，可以通过 `com.alipay.sofa.runtime.SofaFramework` 按图索骥...

**Comment by cxc3214** [comment]
好的，谢谢
