### ISSUE TITLE
SOFARPC 使用的时候有最佳实践吗？

### ISSUE THREAD

**Issue by xiaowan** [alipay/sofa-rpc#60]
我们最近在做微服务框架的调研，关于sofarpc，有什么推荐的用法吗？

**Comment by xiaowan** [comment]
呃，可以理解为最佳实践

**Comment by khotyn** [comment]
@xiaowan 其实按照文档正常使用就可以了，只要注意一般上的 RPC 框架的使用问题，比如说超时的设置，线程池的调优等等就行，这些毕竟每个系统都不一样，如果你们的流量比较大的话，还可以用上预热转发等能力。
