### ISSUE TITLE
com.alipay.sofa.rpc.rest.hostname 的作用 

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#601]
### Your question

[RPC 默认参数配置](https://www.sofastack.tech/sofa-rpc/docs/Application-RPC-Config)中有一个配置: `com.alipay.sofa.rpc.rest.hostname` 不太明白这个参数有什么作用. 

之前遇到过一个 RESTeasy 的一个问题, 服务端不能识别 `GET  http://domain/api/xxx` 这样子带域名的请求, 只能支持`GET  /api/xxx`,这样子的请求. 我的解决方案是升级 RESTeasy 的版本, 是不是这里配置了  `com.alipay.sofa.rpc.rest.hostname`  就行了?

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
不是的，这个值是为了多网卡场景下，rest server 绑定哪个ip 设置的。

**Comment by OrezzerO** [comment]
了解了,十分感谢
