### ISSUE TITLE
sofa-boot默认开启开启Baggage了吗？

### ISSUE THREAD

**Issue by cxc3214** [alipay/sofa-rpc#609]
尝试了ResponseBaggage,RequestBaggage,都不能生效，请问下如何开启？

**Comment by leizhiyuan** [comment]
开启了，麻烦提供复现的demo。

**Comment by cxc3214** [comment]
@leizhiyuan  https://github.com/cxc3214/sofarpc_test 麻烦指点一下哪里错了？

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/57202408-608cc200-6fd7-11e9-9994-75dac6e77682.png)

patch 打上去看下改动，服务端给客户端透传，用ResponseBaggage，客户端给服务端透传用RequestBaggage

[use_baggage.patch.zip](https://github.com/alipay/sofa-rpc/files/3146210/use_baggage.patch.zip)

**Comment by cxc3214** [comment]
好的，谢谢啦

**Comment by cxc3214** [comment]
@leizhiyuan 我想要能在rpc 各个节点之间共享 当前request的用户信息比如 当前登录的用id,
本来是想通过穿透数据传递的，但是在穿透各个上下文之中获取不到requestContext, 有没有办法能够做到，比如filter？
