### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by jy03078584** [alipay/sofa-rpc#61]
### Typo
- [多注册中心](https://github.com/alipay/sofa-rpc/wiki/Features#%E6%9C%8D%E5%8A%A1%E5%8F%91%E5%B8%83%E6%9C%8D%E5%8A%A1%E5%BC%95%E7%94%A8)
![image](https://user-images.githubusercontent.com/7719370/39343373-157311a0-4a0f-11e8-99b6-e7e401acc08a.png)

- [客户端编写](https://github.com/alipay/sofa-rpc/wiki/Getting-Started-with-API#%E7%BC%96%E5%86%99%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%AE%9E%E7%8E%B0)
![image](https://user-images.githubusercontent.com/7719370/39343438-5a598128-4a0f-11e8-94e2-b2a78dcb7cd0.png)

### Improve
请问后面会提供`SofaRPC`代码层的启动链/调用链流程图么。像`Dubbo`那样更能让开发者有全局的印象。

**Comment by leizhiyuan** [comment]
@jy03078584 相关文档我们这边已经更新

https://github.com/alipay/sofa-rpc/wiki/DeveloperGuide#client-%E6%A8%A1%E5%9D%97%E7%BB%84%E4%BB%B6 你说的调用链可以看下这里.

**Comment by jy03078584** [comment]
@leizhiyuan 
谢谢~
下午已经看到了 忘记这个issue了
closed
