### ISSUE TITLE
JAXRSProviderManager 的问题

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#610]
### Your question
`JAXRSProviderManager#registerInternalProviderClass` 这个方法和 `JAXRSProviderManager#registerCustomProviderInstance`这个方法有什么区别吗? 在使用的时候需要注意些什么?
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by JervyShi** [comment]
@OrezzerO  `JAXRSProviderManager#registerInternalProviderClass` 主要用于 SOFA RPC 内部注册的 `Provider` ，入参是 Class ，`JAXRSProviderManager#registerCustomProviderInstance` 是提供给用户扩展用的 `Provider` 注册入口，入参是 Provider 实例，用户可以更自主的构造自己需要的 Provider。

使用上需要注意 `JAXRSProviderManager#registerCustomProviderInstance` 一定要在 SOFA RPC 初始化之前，比如 RPC 的 Service 构造之后，Provider 已确定，此时再注册已无意义。

**Comment by OrezzerO** [comment]
@JervyShi  比如说我实现了一个 `Jackson2Provider`, 我用无参构造函数就可以初始化这个类, 那我现在用这两个方法有区别吗?
方法 1:
```java
registerInternalProviderClass(Jackson2Provider.class);
```

方法 2 :
```java
registerInternalProviderClass(new Jackson2Provider());
```

**Comment by JervyShi** [comment]
这里的方法 2 应该说的是：
```
registerCustomProviderInstance(new Jackson2Provider())
```
无参构造函数就可以初始化的类这两种用法没什么差别。

**Comment by OrezzerO** [comment]
了解了,十分感谢!
