### ISSUE TITLE
Make SOFARPC's dependency on healthcheck optional

### ISSUE THREAD

**Issue by khotyn** [alipay/sofa-rpc#63]
SOFARPC's dependency on healthcheck should be optional, when there is no healthcheck related dependencies, healthcheck ability of SOFARPC should be disabled.

**Comment by leizhiyuan** [comment]
see https://github.com/alipay/sofa-rpc-boot-projects/issues/29

I will close this issue ,https://github.com/alipay/sofa-rpc-boot-projects/issues/29, this featrue will be done here.
