### ISSUE TITLE
链路数据透传的 demo 好像有误？

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-rpc#74]
![sofa-fail.png](https://upload-images.jianshu.io/upload_images/4236553-7c8a539476b63ace.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by leizhiyuan** [comment]
fix
https://github.com/alipay/sofa-rpc/wiki/Invoke-Chain-Pass-Data
