### ISSUE TITLE
预热权重的算法的疑问？

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-rpc#82]
你好，关于预热权重的功能，我有个疑问，我看的是 RandomLoadBalancer 类，该类的 doSelect 方法会判断如果服务列表中的权重不同，会进行一个选择，即第二个 if 块的代码。

```java
  if (totalWeight > 0 && !isWeightSame) {
        // 如果权重不相同且权重大于0则按总权重数随机
        int offset = random.nextInt(totalWeight);
        // 并确定随机值落在哪个片断上
        for (int i = 0; i < size; i++) {
            offset -= getWeight(providerInfos.get(i));
            if (offset < 0) {
                providerInfo = providerInfos.get(i);
                break;
            }
        }
    }
```

我推导了一下：

假设有 A， B， C， 3 个服务，每个服务默认权重 100，其中 C 现在处于预热阶段，则 C 的权重等于 10.

那么总权重 210。

随机一个数，
假设是 200，那么当这个算法运行结束，C，永远不会被选择到；
假设这个随机数是 201，那么当这个算法运行结束，极有可能会击中 C（C 在最后一位，即集合的排序是倒序）。但如果 C 在第二位或者第一位，那么，C 就不会被击中。这样是不是不够公平？

并且我好像没有从代码中看到对服务列表进行倒序。

还请您解答！谢谢！

**Comment by NeGnail** [comment]
每次调用都会生成一个新的随机数,因此每次选择的结果是不一样的。   另外,如果是A:100,B:100,C10的权重比例，如果随机数是200，那么应该选择到C吧。

**Comment by liangyuanpeng** [comment]
@stateIs0 
按照你的说法，测试了一下代码。
假设有 A， B， C， 3 个服务，每个服务默认权重 100，其中 C 现在处于预热阶段，则 C 的权重等于 10.

for循环50次，是有几率获取到服务C的

**Comment by leizhiyuan** [comment]
这是求线段 落点概率,以下个数表示权重

AAAAABBBC
123456789

如果随机到1-5,从左到右-A 的权重<0,就表示进入 A 的范围, 概率是5/9
如果随机到6-8,从左到右-A-B 的权重 之后<0,就表示进入 B 的范围, 概率是3/9
如果随机到9,就表示进入 C 的范围, 概率是1/9

跟权重相对应.

**Comment by stateIs0** [comment]
@NeGnail 您好，200 的例子确实不对，应该是 199.
@leizhiyuan  您好，我的疑惑的地方是：如果在199以内，那么 C 肯定不会被击中，这个没有问题。如果在 200-209 内，按照权重，是否应该一定被击中呢？如果不能保证一定击中，是否权重会不公平呢？

**Comment by stateIs0** [comment]
@leizhiyuan 还有，您的例子就是排序好的啊，如果排序是 ：
CAAAAABBB
123456789

这样的话，权重还能保证吗？

**Comment by NeGnail** [comment]
如果在 200-209 内，按照权重，会选中到C。这里为什么不是一定被选中？

**Comment by stateIs0** [comment]
@NeGnail 如果 C 在第一位或者第二位，那么肯定不会选中它啊？除非他在最后一位。所以我疑惑的地方就是没有倒序啊。

**Comment by liangyuanpeng** [comment]
@stateIs0 
如果C是在第一位，那么一定会选中C的情况是权重落在0-9之间
如果C落在第二位，那么一定会选中C的情况是权重落在100-109之间
如果C是在第三位，那么一定会选中C的情况是权重落在200-209

**Comment by NeGnail** [comment]
如果C在第一位，随机数如果为200-209，不会选到C。

此时选到C的随机数是0-9，所有随机数可能情况是210。几率还是10/210。      无论顺序是怎样的，这个算法里面，ABC三个节点被选择的几率都是对应权重的。

**Comment by stateIs0** [comment]
@liangyuanpeng @NeGnail  完美。是这样的，谢谢你们的耐心解答。
