### ISSUE TITLE
自动故障剔除降级恢复策略疑惑

### ISSUE THREAD

**Issue by SteNicholas** [alipay/sofa-rpc#84]
您好，关于自动故障剔除功能降级恢复策略，目前主要的降级策略就是权重降级策略即WeightDegradeStrategy类，也就是根据自定义配置的weightDegradeRate来调整Provider的权重
`// degrade weight of this provider info`
`boolean success = ProviderInfoWeightManager.degradeWeight(providerInfo, degradeWeight);`
除此之外还有别的降级策略比如说返回常量值，抛出指定异常等等吗?降级策略可以自定义配置吗?
另外，SOFARPC的恢复策略即权重恢复策略WeightRecoverStrategy类也就是如下代码处理：
`int recoverWeight = CalculateUtils.multiply(currentWeight, weightRecoverRate);`
 `int originWeight = statDimension.getOriginWeight();`
` // recover weight of this provider info`
 `if (recoverWeight >= originWeight) {`
 `    measureResultDetail.setRecoveredOriginWeight(true);`
 `    ProviderInfoWeightManager.recoverOriginWeight(providerInfo, originWeight);`
直接根据配置的weightRecoverRate恢复比率参数来更新Provider的权重，这边能按照阶梯式的恢复比率逐渐放量恢复而不是自定义配置恢复比率呢？

**Comment by SteNicholas** [comment]
关于熔断故障注入组件功能有开源计划吗？

**Comment by leizhiyuan** [comment]
@SteNicholas 熔断故障注入这块是一个新的组件,不是 rpc 这边,因为故障注入不仅限于 rpc,具体的 开源计划可以关注https://github.com/alipay 这个 group 下的产品,或者在微信群中咨询,相关的同学会回复.

**Comment by SteNicholas** [comment]
好的，非常感谢 @leizhiyuan 解答。

**Comment by jiaobuchong** [comment]
1、看代码，对实例进行权重降级的时候不能降为 0 吧？因为当服务异常的时候，是希望可以直接将节点摘除的，自动故障剔除是不支持的吗？
2、现在的做法是权重降级最低是 1，然后等着有流量进来没有异常率就恢复，如果一直没流量进来，就不会恢复？
